CREATE DATABASE IF NOT EXISTS {{ db }}
    COMMENT = 'Synthetic Retail Bank - Development Database';

CREATE SCHEMA IF NOT EXISTS {{ db }}.AAA_DCM;

CREATE DCM PROJECT IF NOT EXISTS {{ db }}.AAA_DCM.SYNTHETIC_RETAIL_BANK;
