CREATE DATABASE IF NOT EXISTS AAA_DEV_SYNTHETIC_BANK
    COMMENT = 'Synthetic Retail Bank - Development Database';

USE DATABASE AAA_DEV_SYNTHETIC_BANK;

CREATE SCHEMA IF NOT EXISTS PUBLIC
    COMMENT = 'Default schema - DCM project container';

CREATE DCM PROJECT IF NOT EXISTS AAA_DEV_SYNTHETIC_BANK.PUBLIC.SYNTHETIC_RETAIL_BANK;
