CREATE DATABASE IF NOT EXISTS AAA_DEV_SYNTHETIC_BANK
    COMMENT = 'Synthetic Retail Bank - Development Database';

USE DATABASE AAA_DEV_SYNTHETIC_BANK;

CREATE SCHEMA IF NOT EXISTS PUBLIC
    COMMENT = 'Default schema - DCM project container';

CREATE DCM PROJECT IF NOT EXISTS AAA_DEV_SYNTHETIC_BANK.PUBLIC.SYNTHETIC_RETAIL_BANK;

CALL SYSTEM$REQUEST_LISTING_AND_WAIT('GZT1ZVEJH9');
CALL SYSTEM$ACCEPT_LEGAL_TERMS('DATA_EXCHANGE_LISTING', 'GZT1ZVEJH9');

CREATE DATABASE IF NOT EXISTS AAA_DEV_SYNTHETIC_BANK_REF_DAP_GLOBAL_SANCTIONS_DATA_SET
    FROM LISTING 'GZT1ZVEJH9';
