/*
 * execute_all_tasks_and_refresh_dts.sql
 * Manually execute all tasks and refresh all dynamic tables
 *
 * EXECUTION ORDER:
 * 1. Execute RAW layer tasks (load data from stages)
 * 2. Refresh AGG layer dynamic tables (transform raw data)
 * 3. Refresh REPORTING layer dynamic tables (business logic)
 *
 * NOTE: 17 child tasks auto-triggered (15 cleanup + 1 customer status + 1 DocAI flatten)
 */

USE DATABASE {{ db }};

-- ============================================================
-- STEP 1: EXECUTE RAW LAYER TASKS
-- ============================================================

-- {{ crm_raw }} (6 root tasks)
USE SCHEMA {{ crm_raw }};
EXECUTE TASK CRMI_RAW_TASK_LOAD_CUSTOMERS;
EXECUTE TASK CRMI_RAW_TASK_LOAD_ADDRESSES;
EXECUTE TASK CRMI_RAW_TASK_LOAD_EXPOSED_PERSON;
EXECUTE TASK CRMI_RAW_TASK_LOAD_CUSTOMER_EVENTS;
EXECUTE TASK EMPI_RAW_TASK_LOAD_EMPLOYEES;
EXECUTE TASK EMPI_RAW_TASK_LOAD_ASSIGNMENTS;
EXECUTE TASK ACCI_RAW_TASK_LOAD_ACCOUNTS;

-- {{ ref_raw }} (1 task)
USE SCHEMA {{ ref_raw }};
EXECUTE TASK REFI_RAW_TASK_LOAD_FX_RATES;

-- {{ pay_raw }} (2 tasks)
USE SCHEMA {{ pay_raw }};
EXECUTE TASK PAYI_RAW_TASK_LOAD_TRANSACTIONS;
EXECUTE TASK ICGI_RAW_TASK_LOAD_SWIFT_MESSAGES;

-- {{ eqt_raw }} (1 task)
USE SCHEMA {{ eqt_raw }};
EXECUTE TASK EQTI_RAW_TASK_LOAD_TRADES;

-- {{ fii_raw }} (1 task)
USE SCHEMA {{ fii_raw }};
EXECUTE TASK FIII_LOAD_TRADES_TASK;

-- {{ cmd_raw }} (1 task)
USE SCHEMA {{ cmd_raw }};
EXECUTE TASK CMDI_LOAD_TRADES_TASK;

-- {{ loa_raw }} (1 root task, auto-triggers FLAT_MAIL_DATA)
USE SCHEMA {{ loa_raw }};
EXECUTE TASK LOAI_RAW_TASK_EXTRACT_MAIL_DATA;

-- {{ rep_raw }} (2 tasks - FINMA LCR)
USE SCHEMA {{ rep_raw }};
EXECUTE TASK LIQI_RAW_TASK_LOAD_HQLA_HOLDINGS;
EXECUTE TASK LIQI_RAW_TASK_LOAD_DEPOSIT_BALANCES;

-- ============================================================
-- STEP 2: REFRESH AGGREGATION LAYER DYNAMIC TABLES
-- ============================================================

-- {{ crm_agg }} (10 DTs: 6 CRM + 1 Account + 3 Employee)
USE SCHEMA {{ crm_agg }};
ALTER DYNAMIC TABLE CRMA_AGG_DT_ADDRESSES_CURRENT REFRESH;
ALTER DYNAMIC TABLE CRMA_AGG_DT_ADDRESSES_HISTORY REFRESH;
ALTER DYNAMIC TABLE CRMA_AGG_DT_CUSTOMER_CURRENT REFRESH;
ALTER DYNAMIC TABLE CRMA_AGG_DT_CUSTOMER_HISTORY REFRESH;
ALTER DYNAMIC TABLE CRMA_AGG_DT_CUSTOMER_LIFECYCLE REFRESH;
ALTER DYNAMIC TABLE CRMA_AGG_DT_CUSTOMER_360 REFRESH;
ALTER DYNAMIC TABLE ACCA_AGG_DT_ACCOUNTS REFRESH;
ALTER DYNAMIC TABLE EMPA_AGG_DT_ADVISOR_PERFORMANCE REFRESH;
ALTER DYNAMIC TABLE EMPA_AGG_DT_TEAM_LEADER_DASHBOARD REFRESH;
ALTER DYNAMIC TABLE EMPA_AGG_DT_PORTFOLIO_BY_ADVISOR REFRESH;

-- {{ ref_agg }} (1 DT)
USE SCHEMA {{ ref_agg }};
ALTER DYNAMIC TABLE REFA_AGG_DT_FX_RATES_ENHANCED REFRESH;

-- {{ pay_agg }} (6 DTs)
USE SCHEMA {{ pay_agg }};
ALTER DYNAMIC TABLE PAYA_AGG_DT_TRANSACTION_ANOMALIES REFRESH;
ALTER DYNAMIC TABLE PAYA_AGG_DT_ACCOUNT_BALANCES REFRESH;
ALTER DYNAMIC TABLE PAYA_AGG_DT_CUSTOMER_TRANSACTION_SUMMARY REFRESH;
ALTER DYNAMIC TABLE ICGA_AGG_DT_SWIFT_PACS008 REFRESH;
ALTER DYNAMIC TABLE ICGA_AGG_DT_SWIFT_PACS002 REFRESH;
ALTER DYNAMIC TABLE ICGA_AGG_DT_SWIFT_PAYMENT_LIFECYCLE REFRESH;

-- {{ eqt_agg }} (3 DTs)
USE SCHEMA {{ eqt_agg }};
ALTER DYNAMIC TABLE EQTA_AGG_DT_TRADE_SUMMARY REFRESH;
ALTER DYNAMIC TABLE EQTA_AGG_DT_PORTFOLIO_POSITIONS REFRESH;
ALTER DYNAMIC TABLE EQTA_AGG_DT_CUSTOMER_ACTIVITY REFRESH;

-- {{ fii_agg }} (5 DTs)
USE SCHEMA {{ fii_agg }};
ALTER DYNAMIC TABLE FIIA_AGG_DT_TRADE_SUMMARY REFRESH;
ALTER DYNAMIC TABLE FIIA_AGG_DT_PORTFOLIO_POSITIONS REFRESH;
ALTER DYNAMIC TABLE FIIA_AGG_DT_DURATION_ANALYSIS REFRESH;
ALTER DYNAMIC TABLE FIIA_AGG_DT_CREDIT_EXPOSURE REFRESH;
ALTER DYNAMIC TABLE FIIA_AGG_DT_YIELD_CURVE REFRESH;

-- {{ cmd_agg }} (5 DTs)
USE SCHEMA {{ cmd_agg }};
ALTER DYNAMIC TABLE CMDA_AGG_DT_TRADE_SUMMARY REFRESH;
ALTER DYNAMIC TABLE CMDA_AGG_DT_PORTFOLIO_POSITIONS REFRESH;
ALTER DYNAMIC TABLE CMDA_AGG_DT_DELTA_EXPOSURE REFRESH;
ALTER DYNAMIC TABLE CMDA_AGG_DT_VOLATILITY_ANALYSIS REFRESH;
ALTER DYNAMIC TABLE CMDA_AGG_DT_DELIVERY_SCHEDULE REFRESH;

-- ============================================================
-- STEP 3: REFRESH REPORTING LAYER DYNAMIC TABLES
-- ============================================================

USE SCHEMA {{ rep_agg }};

-- Core Reporting (9 DTs)
ALTER DYNAMIC TABLE REPP_AGG_DT_CUSTOMER_SUMMARY REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_DAILY_TRANSACTION_SUMMARY REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_CURRENCY_EXPOSURE_CURRENT REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_CURRENCY_EXPOSURE_HISTORY REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_CURRENCY_SETTLEMENT_EXPOSURE REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_ANOMALY_ANALYSIS REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_HIGH_RISK_PATTERNS REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_SETTLEMENT_ANALYSIS REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_LIFECYCLE_ANOMALIES REFRESH;

-- Equity (4 DTs)
ALTER DYNAMIC TABLE REPP_AGG_DT_EQUITY_SUMMARY REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_EQUITY_POSITIONS REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_EQUITY_CURRENCY_EXPOSURE REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_HIGH_VALUE_EQUITY_TRADES REFRESH;

-- Credit Risk (5 DTs)
ALTER DYNAMIC TABLE REPP_AGG_DT_IRB_CUSTOMER_RATINGS REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_IRB_PORTFOLIO_METRICS REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_CUSTOMER_RATING_HISTORY REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_IRB_RWA_SUMMARY REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_IRB_RISK_TRENDS REFRESH;

-- FRTB (4 DTs)
ALTER DYNAMIC TABLE REPP_AGG_DT_FRTB_RISK_POSITIONS REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_FRTB_SENSITIVITIES REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_FRTB_CAPITAL_CHARGES REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_FRTB_NMRF_ANALYSIS REFRESH;

-- BCBS 239 (6 DTs)
ALTER DYNAMIC TABLE REPP_AGG_DT_BCBS239_RISK_AGGREGATION REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_BCBS239_EXECUTIVE_DASHBOARD REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_BCBS239_REGULATORY_REPORTING REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_BCBS239_RISK_CONCENTRATION REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_BCBS239_RISK_LIMITS REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_BCBS239_DATA_QUALITY REFRESH;

-- Portfolio (1 DT)
ALTER DYNAMIC TABLE REPP_AGG_DT_PORTFOLIO_PERFORMANCE REFRESH;

-- LCR (6 DTs)
ALTER DYNAMIC TABLE REPP_AGG_DT_LCR_HQLA REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_LCR_OUTFLOW REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_LCR_HQLA_CALCULATION REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_LCR_OUTFLOW_CALCULATION REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_LCR_DAILY REFRESH;
ALTER DYNAMIC TABLE REPP_AGG_DT_LCR_TREND REFRESH;

-- Loan Portfolio (5 DTs)
ALTER DYNAMIC TABLE LOAR_AGG_DT_PORTFOLIO_SUMMARY REFRESH;
ALTER DYNAMIC TABLE LOAR_AGG_DT_LTV_DISTRIBUTION REFRESH;
ALTER DYNAMIC TABLE LOAR_AGG_DT_APPLICATION_FUNNEL REFRESH;
ALTER DYNAMIC TABLE LOAR_AGG_DT_AFFORDABILITY_SUMMARY REFRESH;
ALTER DYNAMIC TABLE LOAR_AGG_DT_CUSTOMER_LOAN_SUMMARY REFRESH;

SELECT 'COMPLETE' AS status, CURRENT_TIMESTAMP() AS completed_at,
       '16 tasks executed, 71 dynamic tables refreshed' AS summary;
