/*
 * resume_all_tasks_and_dts.sql
 * Resume all suspended tasks and dynamic tables
 *
 * IMPORTANT: Child tasks must be resumed BEFORE parent/root tasks
 */

USE DATABASE AAA_DEV_SYNTHETIC_BANK;

-- ============================================================
-- RESUME DYNAMIC TABLES
-- ============================================================

-- CRM_AGG_001 (10 DTs)
USE SCHEMA CRM_AGG_001;
ALTER DYNAMIC TABLE CRMA_AGG_DT_ADDRESSES_CURRENT RESUME;
ALTER DYNAMIC TABLE CRMA_AGG_DT_ADDRESSES_HISTORY RESUME;
ALTER DYNAMIC TABLE CRMA_AGG_DT_CUSTOMER_CURRENT RESUME;
ALTER DYNAMIC TABLE CRMA_AGG_DT_CUSTOMER_HISTORY RESUME;
ALTER DYNAMIC TABLE CRMA_AGG_DT_CUSTOMER_LIFECYCLE RESUME;
ALTER DYNAMIC TABLE CRMA_AGG_DT_CUSTOMER_360 RESUME;
ALTER DYNAMIC TABLE ACCA_AGG_DT_ACCOUNTS RESUME;
ALTER DYNAMIC TABLE EMPA_AGG_DT_ADVISOR_PERFORMANCE RESUME;
ALTER DYNAMIC TABLE EMPA_AGG_DT_TEAM_LEADER_DASHBOARD RESUME;
ALTER DYNAMIC TABLE EMPA_AGG_DT_PORTFOLIO_BY_ADVISOR RESUME;

-- REF_AGG_001 (1 DT)
USE SCHEMA REF_AGG_001;
ALTER DYNAMIC TABLE REFA_AGG_DT_FX_RATES_ENHANCED RESUME;

-- PAY_AGG_001 (6 DTs)
USE SCHEMA PAY_AGG_001;
ALTER DYNAMIC TABLE PAYA_AGG_DT_TRANSACTION_ANOMALIES RESUME;
ALTER DYNAMIC TABLE PAYA_AGG_DT_ACCOUNT_BALANCES RESUME;
ALTER DYNAMIC TABLE PAYA_AGG_DT_CUSTOMER_TRANSACTION_SUMMARY RESUME;
ALTER DYNAMIC TABLE ICGA_AGG_DT_SWIFT_PACS008 RESUME;
ALTER DYNAMIC TABLE ICGA_AGG_DT_SWIFT_PACS002 RESUME;
ALTER DYNAMIC TABLE ICGA_AGG_DT_SWIFT_PAYMENT_LIFECYCLE RESUME;

-- EQT_AGG_001 (3 DTs)
USE SCHEMA EQT_AGG_001;
ALTER DYNAMIC TABLE EQTA_AGG_DT_TRADE_SUMMARY RESUME;
ALTER DYNAMIC TABLE EQTA_AGG_DT_PORTFOLIO_POSITIONS RESUME;
ALTER DYNAMIC TABLE EQTA_AGG_DT_CUSTOMER_ACTIVITY RESUME;

-- FII_AGG_001 (5 DTs)
USE SCHEMA FII_AGG_001;
ALTER DYNAMIC TABLE FIIA_AGG_DT_TRADE_SUMMARY RESUME;
ALTER DYNAMIC TABLE FIIA_AGG_DT_PORTFOLIO_POSITIONS RESUME;
ALTER DYNAMIC TABLE FIIA_AGG_DT_DURATION_ANALYSIS RESUME;
ALTER DYNAMIC TABLE FIIA_AGG_DT_CREDIT_EXPOSURE RESUME;
ALTER DYNAMIC TABLE FIIA_AGG_DT_YIELD_CURVE RESUME;

-- CMD_AGG_001 (5 DTs)
USE SCHEMA CMD_AGG_001;
ALTER DYNAMIC TABLE CMDA_AGG_DT_TRADE_SUMMARY RESUME;
ALTER DYNAMIC TABLE CMDA_AGG_DT_PORTFOLIO_POSITIONS RESUME;
ALTER DYNAMIC TABLE CMDA_AGG_DT_DELTA_EXPOSURE RESUME;
ALTER DYNAMIC TABLE CMDA_AGG_DT_VOLATILITY_ANALYSIS RESUME;
ALTER DYNAMIC TABLE CMDA_AGG_DT_DELIVERY_SCHEDULE RESUME;

-- REP_AGG_001 (35 DTs)
USE SCHEMA REP_AGG_001;
ALTER DYNAMIC TABLE REPP_AGG_DT_CUSTOMER_SUMMARY RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_DAILY_TRANSACTION_SUMMARY RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_CURRENCY_EXPOSURE_CURRENT RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_CURRENCY_EXPOSURE_HISTORY RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_CURRENCY_SETTLEMENT_EXPOSURE RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_ANOMALY_ANALYSIS RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_HIGH_RISK_PATTERNS RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_SETTLEMENT_ANALYSIS RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_LIFECYCLE_ANOMALIES RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_EQUITY_SUMMARY RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_EQUITY_POSITIONS RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_EQUITY_CURRENCY_EXPOSURE RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_HIGH_VALUE_EQUITY_TRADES RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_IRB_CUSTOMER_RATINGS RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_IRB_PORTFOLIO_METRICS RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_CUSTOMER_RATING_HISTORY RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_IRB_RWA_SUMMARY RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_IRB_RISK_TRENDS RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_FRTB_RISK_POSITIONS RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_FRTB_SENSITIVITIES RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_FRTB_CAPITAL_CHARGES RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_FRTB_NMRF_ANALYSIS RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_BCBS239_RISK_AGGREGATION RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_BCBS239_EXECUTIVE_DASHBOARD RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_BCBS239_REGULATORY_REPORTING RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_BCBS239_RISK_CONCENTRATION RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_BCBS239_RISK_LIMITS RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_BCBS239_DATA_QUALITY RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_PORTFOLIO_PERFORMANCE RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_LCR_HQLA RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_LCR_OUTFLOW RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_LCR_HQLA_CALCULATION RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_LCR_OUTFLOW_CALCULATION RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_LCR_DAILY RESUME;
ALTER DYNAMIC TABLE REPP_AGG_DT_LCR_TREND RESUME;
ALTER DYNAMIC TABLE LOAR_AGG_DT_PORTFOLIO_SUMMARY RESUME;
ALTER DYNAMIC TABLE LOAR_AGG_DT_LTV_DISTRIBUTION RESUME;
ALTER DYNAMIC TABLE LOAR_AGG_DT_APPLICATION_FUNNEL RESUME;
ALTER DYNAMIC TABLE LOAR_AGG_DT_AFFORDABILITY_SUMMARY RESUME;
ALTER DYNAMIC TABLE LOAR_AGG_DT_CUSTOMER_LOAN_SUMMARY RESUME;

-- ============================================================
-- RESUME TASKS (child tasks BEFORE root tasks)
-- ============================================================

-- CRM_RAW_001 (13 tasks: children first, then roots)
USE SCHEMA CRM_RAW_001;
ALTER TASK CRMI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_CUSTOMERS RESUME;
ALTER TASK CRMI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_ADDRESSES RESUME;
ALTER TASK CRMI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_EXPOSED_PERSON RESUME;
ALTER TASK CRMI_RAW_TASK_LOAD_CUSTOMER_STATUS RESUME;
ALTER TASK EMPI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_EMPLOYEES RESUME;
ALTER TASK EMPI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_ASSIGNMENTS RESUME;
ALTER TASK ACCI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_ACCOUNTS RESUME;
ALTER TASK CRMI_RAW_TASK_LOAD_CUSTOMERS RESUME;
ALTER TASK CRMI_RAW_TASK_LOAD_ADDRESSES RESUME;
ALTER TASK CRMI_RAW_TASK_LOAD_EXPOSED_PERSON RESUME;
ALTER TASK CRMI_RAW_TASK_LOAD_CUSTOMER_EVENTS RESUME;
ALTER TASK EMPI_RAW_TASK_LOAD_EMPLOYEES RESUME;
ALTER TASK EMPI_RAW_TASK_LOAD_ASSIGNMENTS RESUME;
ALTER TASK ACCI_RAW_TASK_LOAD_ACCOUNTS RESUME;

-- REF_RAW_001 (2 tasks)
USE SCHEMA REF_RAW_001;
ALTER TASK REFI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_FX_RATES RESUME;
ALTER TASK REFI_RAW_TASK_LOAD_FX_RATES RESUME;

-- PAY_RAW_001 (4 tasks)
USE SCHEMA PAY_RAW_001;
ALTER TASK PAYI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_TRANSACTIONS RESUME;
ALTER TASK ICGI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_SWIFT_MESSAGES RESUME;
ALTER TASK PAYI_RAW_TASK_LOAD_TRANSACTIONS RESUME;
ALTER TASK ICGI_RAW_TASK_LOAD_SWIFT_MESSAGES RESUME;

-- EQT_RAW_001 (2 tasks)
USE SCHEMA EQT_RAW_001;
ALTER TASK EQTI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_TRADES RESUME;
ALTER TASK EQTI_RAW_TASK_LOAD_TRADES RESUME;

-- FII_RAW_001 (2 tasks)
USE SCHEMA FII_RAW_001;
ALTER TASK FIII_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_TRADES RESUME;
ALTER TASK FIII_LOAD_TRADES_TASK RESUME;

-- CMD_RAW_001 (2 tasks)
USE SCHEMA CMD_RAW_001;
ALTER TASK CMDI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_TRADES RESUME;
ALTER TASK CMDI_LOAD_TRADES_TASK RESUME;

-- LOA_RAW_001 (2 tasks: child first)
USE SCHEMA LOA_RAW_001;
ALTER TASK LOAI_RAW_TASK_FLAT_MAIL_DATA RESUME;
ALTER TASK LOAI_RAW_TASK_EXTRACT_MAIL_DATA RESUME;

-- REP_RAW_001 (4 tasks)
USE SCHEMA REP_RAW_001;
ALTER TASK LIQI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_HQLA_HOLDINGS RESUME;
ALTER TASK LIQI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_DEPOSIT_BALANCES RESUME;
ALTER TASK LIQI_RAW_TASK_LOAD_HQLA_HOLDINGS RESUME;
ALTER TASK LIQI_RAW_TASK_LOAD_DEPOSIT_BALANCES RESUME;

SELECT 'RESUME COMPLETE' AS status, CURRENT_TIMESTAMP() AS completed_at,
       '71 DTs and 32 tasks resumed' AS summary;
