-- ============================================================
-- One-time setup (requires ACCOUNTADMIN)
-- Run: snow sql -c <connection> --role ACCOUNTADMIN -f operation/setup_listings.sql
-- ============================================================

-- Step 1: Accept the Global Sanctions Data listing
CREATE DATABASE IF NOT EXISTS AAA_DEV_SYNTHETIC_BANK_REF_DAP_GLOBAL_SANCTIONS_DATA_SET
    FROM LISTING 'GZT1ZVEJH9';

-- Step 2: Create local copy database for fuzzy matching
CREATE OR REPLACE DATABASE AAA_DEV_SYNTHETIC_BANK_REF_DAP_GLOBAL_SANCTIONS_DATA_SET_COPY
    COMMENT = 'Local copy of Global Sanctions Data for staging table creation and fuzzy matching.';

USE DATABASE AAA_DEV_SYNTHETIC_BANK_REF_DAP_GLOBAL_SANCTIONS_DATA_SET_COPY;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE PUBLIC.SANCTIONS_TB_DATA_STAGING AS
SELECT
    "Sr No.",
    ENTITY_ID,
    ENTITY_NAME,
    ENTITY_ALIASES,
    ENTITY_TYPE,
    DOB,
    POB,
    NATIONALITY_COUNTRY,
    CITIZENSHIP_COUNTRY,
    ADDRESS,
    AUTHORITY,
    LIST_NAME,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    ENTITY_NOTES,
    CITATION_LINK,
    COUNTRY,
    LISTING_COUNTRY,
    CALL_SIGN,
    VESSEL_TYPE,
    VESSEL_FLAG,
    VESSEL_OWNER,
    GROSS_TONNAGE,
    GROSS_REGISTERED_TONNAGE,
    CURRENT_DATE AS CREATED_DATE,
    CURRENT_TIMESTAMP AS LAST_UPDATED
FROM AAA_DEV_SYNTHETIC_BANK_REF_DAP_GLOBAL_SANCTIONS_DATA_SET.GLOBAL_SANCTIONS_DATA.SANCTIONS_DATAFEED;

-- Step 3: Grant usage to CICD role
GRANT USAGE ON DATABASE AAA_DEV_SYNTHETIC_BANK_REF_DAP_GLOBAL_SANCTIONS_DATA_SET_COPY TO ROLE CICD;
GRANT USAGE ON SCHEMA AAA_DEV_SYNTHETIC_BANK_REF_DAP_GLOBAL_SANCTIONS_DATA_SET_COPY.PUBLIC TO ROLE CICD;
GRANT SELECT ON ALL TABLES IN SCHEMA AAA_DEV_SYNTHETIC_BANK_REF_DAP_GLOBAL_SANCTIONS_DATA_SET_COPY.PUBLIC TO ROLE CICD;
