/*
 * suspend_all_tasks_and_dts.sql
 * Suspend all tasks and dynamic tables for maintenance
 *
 * IMPORTANT: Root tasks must be suspended BEFORE child tasks
 */

USE DATABASE {{ db }};

-- ============================================================
-- SUSPEND TASKS (root tasks BEFORE child tasks)
-- ============================================================

-- {{ crm_raw }} (13 tasks: roots first, then children)
USE SCHEMA {{ crm_raw }};
ALTER TASK CRMI_RAW_TASK_LOAD_CUSTOMERS SUSPEND;
ALTER TASK CRMI_RAW_TASK_LOAD_ADDRESSES SUSPEND;
ALTER TASK CRMI_RAW_TASK_LOAD_EXPOSED_PERSON SUSPEND;
ALTER TASK CRMI_RAW_TASK_LOAD_CUSTOMER_EVENTS SUSPEND;
ALTER TASK EMPI_RAW_TASK_LOAD_EMPLOYEES SUSPEND;
ALTER TASK EMPI_RAW_TASK_LOAD_ASSIGNMENTS SUSPEND;
ALTER TASK ACCI_RAW_TASK_LOAD_ACCOUNTS SUSPEND;
ALTER TASK CRMI_RAW_TASK_LOAD_CUSTOMER_STATUS SUSPEND;
ALTER TASK CRMI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_CUSTOMERS SUSPEND;
ALTER TASK CRMI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_ADDRESSES SUSPEND;
ALTER TASK CRMI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_EXPOSED_PERSON SUSPEND;
ALTER TASK ACCI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_ACCOUNTS SUSPEND;
ALTER TASK EMPI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_EMPLOYEES SUSPEND;
ALTER TASK EMPI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_ASSIGNMENTS SUSPEND;

-- {{ ref_raw }} (2 tasks)
USE SCHEMA {{ ref_raw }};
ALTER TASK REFI_RAW_TASK_LOAD_FX_RATES SUSPEND;
ALTER TASK REFI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_FX_RATES SUSPEND;

-- {{ pay_raw }} (4 tasks)
USE SCHEMA {{ pay_raw }};
ALTER TASK PAYI_RAW_TASK_LOAD_TRANSACTIONS SUSPEND;
ALTER TASK ICGI_RAW_TASK_LOAD_SWIFT_MESSAGES SUSPEND;
ALTER TASK PAYI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_TRANSACTIONS SUSPEND;
ALTER TASK ICGI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_SWIFT_MESSAGES SUSPEND;

-- {{ eqt_raw }} (2 tasks)
USE SCHEMA {{ eqt_raw }};
ALTER TASK EQTI_RAW_TASK_LOAD_TRADES SUSPEND;
ALTER TASK EQTI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_TRADES SUSPEND;

-- {{ fii_raw }} (2 tasks)
USE SCHEMA {{ fii_raw }};
ALTER TASK FIII_LOAD_TRADES_TASK SUSPEND;
ALTER TASK FIII_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_TRADES SUSPEND;

-- {{ cmd_raw }} (2 tasks)
USE SCHEMA {{ cmd_raw }};
ALTER TASK CMDI_LOAD_TRADES_TASK SUSPEND;
ALTER TASK CMDI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_TRADES SUSPEND;

-- {{ loa_raw }} (2 tasks: root first)
USE SCHEMA {{ loa_raw }};
ALTER TASK IF EXISTS LOAI_RAW_TASK_EXTRACT_MAIL_DATA SUSPEND;
ALTER TASK IF EXISTS LOAI_RAW_TASK_FLAT_MAIL_DATA SUSPEND;

-- {{ rep_raw }} (4 tasks)
USE SCHEMA {{ rep_raw }};
ALTER TASK LIQI_RAW_TASK_LOAD_HQLA_HOLDINGS SUSPEND;
ALTER TASK LIQI_RAW_TASK_LOAD_DEPOSIT_BALANCES SUSPEND;
ALTER TASK LIQI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_HQLA_HOLDINGS SUSPEND;
ALTER TASK LIQI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_DEPOSIT_BALANCES SUSPEND;

-- ============================================================
-- SUSPEND DYNAMIC TABLES
-- ============================================================

-- {{ crm_agg }} (10 DTs)
USE SCHEMA {{ crm_agg }};
ALTER DYNAMIC TABLE CRMA_AGG_DT_ADDRESSES_CURRENT SUSPEND;
ALTER DYNAMIC TABLE CRMA_AGG_DT_ADDRESSES_HISTORY SUSPEND;
ALTER DYNAMIC TABLE CRMA_AGG_DT_CUSTOMER_CURRENT SUSPEND;
ALTER DYNAMIC TABLE CRMA_AGG_DT_CUSTOMER_HISTORY SUSPEND;
ALTER DYNAMIC TABLE CRMA_AGG_DT_CUSTOMER_LIFECYCLE SUSPEND;
ALTER DYNAMIC TABLE CRMA_AGG_DT_CUSTOMER_360 SUSPEND;
ALTER DYNAMIC TABLE ACCA_AGG_DT_ACCOUNTS SUSPEND;
ALTER DYNAMIC TABLE EMPA_AGG_DT_ADVISOR_PERFORMANCE SUSPEND;
ALTER DYNAMIC TABLE EMPA_AGG_DT_TEAM_LEADER_DASHBOARD SUSPEND;
ALTER DYNAMIC TABLE EMPA_AGG_DT_PORTFOLIO_BY_ADVISOR SUSPEND;

-- {{ ref_agg }} (1 DT)
USE SCHEMA {{ ref_agg }};
ALTER DYNAMIC TABLE REFA_AGG_DT_FX_RATES_ENHANCED SUSPEND;

-- {{ pay_agg }} (6 DTs)
USE SCHEMA {{ pay_agg }};
ALTER DYNAMIC TABLE PAYA_AGG_DT_TRANSACTION_ANOMALIES SUSPEND;
ALTER DYNAMIC TABLE PAYA_AGG_DT_ACCOUNT_BALANCES SUSPEND;
ALTER DYNAMIC TABLE PAYA_AGG_DT_CUSTOMER_TRANSACTION_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE ICGA_AGG_DT_SWIFT_PACS008 SUSPEND;
ALTER DYNAMIC TABLE ICGA_AGG_DT_SWIFT_PACS002 SUSPEND;
ALTER DYNAMIC TABLE ICGA_AGG_DT_SWIFT_PAYMENT_LIFECYCLE SUSPEND;

-- {{ eqt_agg }} (3 DTs)
USE SCHEMA {{ eqt_agg }};
ALTER DYNAMIC TABLE EQTA_AGG_DT_TRADE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE EQTA_AGG_DT_PORTFOLIO_POSITIONS SUSPEND;
ALTER DYNAMIC TABLE EQTA_AGG_DT_CUSTOMER_ACTIVITY SUSPEND;

-- {{ fii_agg }} (5 DTs)
USE SCHEMA {{ fii_agg }};
ALTER DYNAMIC TABLE FIIA_AGG_DT_TRADE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE FIIA_AGG_DT_PORTFOLIO_POSITIONS SUSPEND;
ALTER DYNAMIC TABLE FIIA_AGG_DT_DURATION_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE FIIA_AGG_DT_CREDIT_EXPOSURE SUSPEND;
ALTER DYNAMIC TABLE FIIA_AGG_DT_YIELD_CURVE SUSPEND;

-- {{ cmd_agg }} (5 DTs)
USE SCHEMA {{ cmd_agg }};
ALTER DYNAMIC TABLE CMDA_AGG_DT_TRADE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CMDA_AGG_DT_PORTFOLIO_POSITIONS SUSPEND;
ALTER DYNAMIC TABLE CMDA_AGG_DT_DELTA_EXPOSURE SUSPEND;
ALTER DYNAMIC TABLE CMDA_AGG_DT_VOLATILITY_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CMDA_AGG_DT_DELIVERY_SCHEDULE SUSPEND;

-- {{ rep_agg }} (35 DTs)
USE SCHEMA {{ rep_agg }};
ALTER DYNAMIC TABLE REPP_AGG_DT_CUSTOMER_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_DAILY_TRANSACTION_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_CURRENCY_EXPOSURE_CURRENT SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_CURRENCY_EXPOSURE_HISTORY SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_CURRENCY_SETTLEMENT_EXPOSURE SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_ANOMALY_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_HIGH_RISK_PATTERNS SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_SETTLEMENT_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_LIFECYCLE_ANOMALIES SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_EQUITY_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_EQUITY_POSITIONS SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_EQUITY_CURRENCY_EXPOSURE SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_HIGH_VALUE_EQUITY_TRADES SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_IRB_CUSTOMER_RATINGS SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_IRB_PORTFOLIO_METRICS SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_CUSTOMER_RATING_HISTORY SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_IRB_RWA_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_IRB_RISK_TRENDS SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_FRTB_RISK_POSITIONS SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_FRTB_SENSITIVITIES SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_FRTB_CAPITAL_CHARGES SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_FRTB_NMRF_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_BCBS239_RISK_AGGREGATION SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_BCBS239_EXECUTIVE_DASHBOARD SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_BCBS239_REGULATORY_REPORTING SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_BCBS239_RISK_CONCENTRATION SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_BCBS239_RISK_LIMITS SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_BCBS239_DATA_QUALITY SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_PORTFOLIO_PERFORMANCE SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_LCR_HQLA SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_LCR_OUTFLOW SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_LCR_HQLA_CALCULATION SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_LCR_OUTFLOW_CALCULATION SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_LCR_DAILY SUSPEND;
ALTER DYNAMIC TABLE REPP_AGG_DT_LCR_TREND SUSPEND;
ALTER DYNAMIC TABLE LOAR_AGG_DT_PORTFOLIO_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE LOAR_AGG_DT_LTV_DISTRIBUTION SUSPEND;
ALTER DYNAMIC TABLE LOAR_AGG_DT_APPLICATION_FUNNEL SUSPEND;
ALTER DYNAMIC TABLE LOAR_AGG_DT_AFFORDABILITY_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE LOAR_AGG_DT_CUSTOMER_LOAN_SUMMARY SUSPEND;

SELECT 'SUSPEND COMPLETE' AS status, CURRENT_TIMESTAMP() AS completed_at,
       '32 tasks and 71 DTs suspended' AS summary;
