DEFINE STAGE {{ db }}.{{ eqt_raw }}.EQTI_RAW_ST_TRADES
 DIRECTORY = (
 ENABLE = TRUE
 AUTO_REFRESH = TRUE
 )
 COMMENT = 'Internal stage for equity trade CSV files. Expected pattern: *trades*.csv with fields: trade_date, trade_id, customer_id, account_id, symbol, side, quantity, price, etc.';

DEFINE TABLE {{ db }}.{{ eqt_raw }}.EQTI_RAW_TB_TRADES (
 TRADE_DATE TIMESTAMP_NTZ NOT NULL,
 SETTLEMENT_DATE DATE NOT NULL,
 TRADE_ID VARCHAR(50) NOT NULL,
 CUSTOMER_ID VARCHAR(30) NOT NULL,
 ACCOUNT_ID VARCHAR(30) NOT NULL,
 ORDER_ID VARCHAR(50) NOT NULL,
 EXEC_ID VARCHAR(50) NOT NULL,
 SYMBOL VARCHAR(20) NOT NULL,
 ISIN VARCHAR(12),
 SIDE CHAR(1) NOT NULL,
 QUANTITY NUMBER(15,4) NOT NULL WITH TAG ({{ db }}.PUBLIC.SENSITIVITY_LEVEL='restricted'),
 PRICE NUMBER(18,6) NOT NULL,
 CURRENCY VARCHAR(3) NOT NULL,
 GROSS_AMOUNT NUMBER(18,2) NOT NULL WITH TAG ({{ db }}.PUBLIC.SENSITIVITY_LEVEL='restricted'),
 COMMISSION NUMBER(12,4) NOT NULL WITH TAG ({{ db }}.PUBLIC.SENSITIVITY_LEVEL='restricted'),
 NET_AMOUNT NUMBER(18,2) NOT NULL WITH TAG ({{ db }}.PUBLIC.SENSITIVITY_LEVEL='restricted'),
 BASE_CURRENCY VARCHAR(3) NOT NULL DEFAULT 'CHF',
 BASE_GROSS_AMOUNT NUMBER(18,2) NOT NULL WITH TAG ({{ db }}.PUBLIC.SENSITIVITY_LEVEL='restricted'),
 BASE_NET_AMOUNT NUMBER(18,2) NOT NULL WITH TAG ({{ db }}.PUBLIC.SENSITIVITY_LEVEL='restricted'),
 FX_RATE NUMBER(12,6) NOT NULL,
 MARKET VARCHAR(10) NOT NULL,
 ORDER_TYPE VARCHAR(15) NOT NULL,
 EXEC_TYPE VARCHAR(15) NOT NULL,
 TIME_IN_FORCE VARCHAR(10),
 BROKER_ID VARCHAR(20),
 VENUE VARCHAR(20),

 CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

 CONSTRAINT PK_EQTI_RAW_TB_TRADES PRIMARY KEY (TRADE_ID),
 CONSTRAINT FK_EQTI_RAW_TB_EQUITY_TRADES__ACCI_RAW_TB_ACCOUNTS FOREIGN KEY (ACCOUNT_ID) REFERENCES {{ db }}.{{ crm_raw }}.ACCI_RAW_TB_ACCOUNTS(ACCOUNT_ID)
)
CHANGE_TRACKING = TRUE
COMMENT = 'Equity trades via FIX protocol with CHF as base currency. Uses INVESTMENT accounts from ACCI_RAW_TB_ACCOUNTS. Signed amounts: positive for purchases, negative for sales.';

DEFINE TASK {{ db }}.{{ eqt_raw }}.EQTI_RAW_TK_LOAD_TRADES
 USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
 SCHEDULE = '60 MINUTE'
 WHEN SYSTEM$STREAM_HAS_DATA('{{ db }}.{{ eqt_raw }}.EQTI_RAW_SM_TRADES_FILES')
AS
 COPY INTO {{ eqt_raw }}.EQTI_RAW_TB_TRADES (TRADE_DATE, SETTLEMENT_DATE, TRADE_ID, CUSTOMER_ID, ACCOUNT_ID, ORDER_ID, EXEC_ID, SYMBOL, ISIN, SIDE, QUANTITY, PRICE, CURRENCY, GROSS_AMOUNT, COMMISSION, NET_AMOUNT, BASE_CURRENCY, BASE_GROSS_AMOUNT, BASE_NET_AMOUNT, FX_RATE, MARKET, ORDER_TYPE, EXEC_TYPE, TIME_IN_FORCE, BROKER_ID, VENUE)
 FROM @EQTI_RAW_ST_TRADES
 PATTERN = '.*trades.*\.csv'
 FILE_FORMAT = EQTI_RAW_FF_TRADES_CSV
 ON_ERROR = CONTINUE;

DEFINE TASK {{ db }}.{{ eqt_raw }}.EQTI_RAW_TK_CLEANUP_AFTER_LOAD_TRADES
 USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
 COMMENT = 'Automated stage cleanup AFTER equity trade data load. Keeps last 5 files to manage storage costs.'
 AFTER {{ db }}.{{ eqt_raw }}.EQTI_RAW_TK_LOAD_TRADES
AS
 CALL EQTI_RAW_SP_CLEANUP_STAGE_KEEP_LAST_N('EQTI_RAW_ST_TRADES', 5);
