DEFINE STAGE {{ db }}.{{ fii_raw }}.FIII_RAW_ST_TRADES
 DIRECTORY = (
 ENABLE = TRUE
 AUTO_REFRESH = TRUE
 )
 COMMENT = 'Internal stage for fixed income trade CSV files. Expected pattern: *fixed_income_trades*.csv with fields: trade_date, trade_id, customer_id, account_id, instrument_type, notional, price, etc.';

DEFINE TABLE {{ db }}.{{ fii_raw }}.FIII_RAW_TB_TRADES (
 TRADE_DATE TIMESTAMP_NTZ,
 SETTLEMENT_DATE DATE,
 TRADE_ID VARCHAR(50) PRIMARY KEY,
 CUSTOMER_ID VARCHAR(30),
 ACCOUNT_ID VARCHAR(30),
 ORDER_ID VARCHAR(50),

 INSTRUMENT_TYPE VARCHAR(10),
 INSTRUMENT_ID VARCHAR(50),
 ISSUER VARCHAR(100),
 ISSUER_TYPE VARCHAR(20),
 CURRENCY VARCHAR(3),
 SIDE VARCHAR(1),

 NOTIONAL FLOAT WITH TAG ({{ db }}.PUBLIC.SENSITIVITY_LEVEL='restricted'),
 PRICE FLOAT,
 ACCRUED_INTEREST FLOAT WITH TAG ({{ db }}.PUBLIC.SENSITIVITY_LEVEL='restricted'),
 GROSS_AMOUNT FLOAT WITH TAG ({{ db }}.PUBLIC.SENSITIVITY_LEVEL='restricted'),
 COMMISSION FLOAT WITH TAG ({{ db }}.PUBLIC.SENSITIVITY_LEVEL='restricted'),
 NET_AMOUNT FLOAT WITH TAG ({{ db }}.PUBLIC.SENSITIVITY_LEVEL='restricted'),

 BASE_CURRENCY VARCHAR(3),
 BASE_GROSS_AMOUNT FLOAT WITH TAG ({{ db }}.PUBLIC.SENSITIVITY_LEVEL='restricted'),
 BASE_NET_AMOUNT FLOAT WITH TAG ({{ db }}.PUBLIC.SENSITIVITY_LEVEL='restricted'),
 FX_RATE FLOAT,

 FIXED_RATE FLOAT,
 FLOATING_RATE_INDEX VARCHAR(20),
 TENOR_YEARS FLOAT,

 COUPON_RATE FLOAT,
 MATURITY_DATE DATE,
 DURATION FLOAT,
 DV01 FLOAT,
 CREDIT_RATING VARCHAR(10),
 CREDIT_SPREAD_BPS FLOAT,

 MARKET VARCHAR(50),
 BROKER_ID VARCHAR(50),
 VENUE VARCHAR(50),
 LIQUIDITY_SCORE FLOAT,

 CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CHANGE_TRACKING = TRUE
COMMENT = 'Raw fixed income trades (bonds and swaps) with FRTB risk metrics';

DEFINE TASK {{ db }}.{{ fii_raw }}.FIII_RAW_TK_LOAD_TRADES
 USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
 SCHEDULE = '60 MINUTE'
 WHEN SYSTEM$STREAM_HAS_DATA('{{ db }}.{{ fii_raw }}.FIII_RAW_SM_TRADES_FILES')
AS
 COPY INTO {{ fii_raw }}.FIII_RAW_TB_TRADES (
 TRADE_DATE, SETTLEMENT_DATE, TRADE_ID, CUSTOMER_ID, ACCOUNT_ID, ORDER_ID,
 INSTRUMENT_TYPE, INSTRUMENT_ID, ISSUER, ISSUER_TYPE, CURRENCY, SIDE,
 NOTIONAL, PRICE, ACCRUED_INTEREST, GROSS_AMOUNT, FIXED_RATE, FLOATING_RATE_INDEX, TENOR_YEARS,
 COMMISSION, NET_AMOUNT, BASE_CURRENCY, BASE_GROSS_AMOUNT, BASE_NET_AMOUNT, FX_RATE,
 COUPON_RATE, MATURITY_DATE, DURATION, DV01, CREDIT_RATING, CREDIT_SPREAD_BPS,
 MARKET, BROKER_ID, VENUE, LIQUIDITY_SCORE
 )
 FROM @FIII_RAW_ST_TRADES
 PATTERN = '.*fixed_income_trades.*\.csv'
 FILE_FORMAT = FIII_RAW_FF_TRADES_CSV
 ON_ERROR = CONTINUE;

DEFINE TASK {{ db }}.{{ fii_raw }}.FIII_RAW_TK_CLEANUP_AFTER_LOAD_TRADES
 USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
 COMMENT = 'Automated stage cleanup AFTER fixed income trade data load. Keeps last 5 files to manage storage costs.'
 AFTER {{ db }}.{{ fii_raw }}.FIII_RAW_TK_LOAD_TRADES
AS
 CALL FIII_RAW_SP_CLEANUP_STAGE_KEEP_LAST_N('FIII_RAW_ST_TRADES', 5);
