DEFINE STAGE {{ db }}.{{ cmd_raw }}.CMDI_RAW_ST_TRADES
 DIRECTORY = (
 ENABLE = TRUE
 AUTO_REFRESH = TRUE
 )
 COMMENT = 'Internal stage for commodity trade CSV files. Expected pattern: *commodity_trades*.csv with fields: trade_date, trade_id, customer_id, account_id, commodity_type, quantity, price, etc.';

DEFINE TABLE {{ db }}.{{ cmd_raw }}.CMDI_RAW_TB_TRADES (
 TRADE_DATE TIMESTAMP_NTZ,
 SETTLEMENT_DATE DATE,
 TRADE_ID VARCHAR(50) PRIMARY KEY,
 CUSTOMER_ID VARCHAR(30),
 ACCOUNT_ID VARCHAR(30),
 ORDER_ID VARCHAR(50),

 COMMODITY_TYPE VARCHAR(20),
 COMMODITY_NAME VARCHAR(50),
 COMMODITY_CODE VARCHAR(10),
 CONTRACT_TYPE VARCHAR(10),

 SIDE VARCHAR(1),
 QUANTITY FLOAT WITH TAG ({{ db }}.PUBLIC.SENSITIVITY_LEVEL='restricted'),
 UNIT VARCHAR(20),
 PRICE FLOAT,
 CURRENCY VARCHAR(3),

 GROSS_AMOUNT FLOAT WITH TAG ({{ db }}.PUBLIC.SENSITIVITY_LEVEL='restricted'),
 COMMISSION FLOAT WITH TAG ({{ db }}.PUBLIC.SENSITIVITY_LEVEL='restricted'),
 NET_AMOUNT FLOAT WITH TAG ({{ db }}.PUBLIC.SENSITIVITY_LEVEL='restricted'),

 BASE_CURRENCY VARCHAR(3),
 BASE_GROSS_AMOUNT FLOAT WITH TAG ({{ db }}.PUBLIC.SENSITIVITY_LEVEL='restricted'),
 BASE_NET_AMOUNT FLOAT,
 FX_RATE FLOAT,

 CONTRACT_SIZE FLOAT,
 NUM_CONTRACTS FLOAT,
 DELIVERY_MONTH VARCHAR(7),
 DELIVERY_LOCATION VARCHAR(100),

 DELTA FLOAT,
 VEGA FLOAT,
 SPOT_PRICE FLOAT,
 FORWARD_PRICE FLOAT,
 VOLATILITY FLOAT,
 LIQUIDITY_SCORE FLOAT,

 EXCHANGE VARCHAR(20),
 BROKER_ID VARCHAR(50),
 VENUE VARCHAR(50),

 CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CHANGE_TRACKING = TRUE
COMMENT = 'Raw commodity trades (energy, metals, agricultural) with FRTB risk metrics';

DEFINE TASK {{ db }}.{{ cmd_raw }}.CMDI_RAW_TK_LOAD_TRADES
 USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
 SCHEDULE = '60 MINUTE'
 WHEN SYSTEM$STREAM_HAS_DATA('{{ db }}.{{ cmd_raw }}.CMDI_RAW_SM_TRADES_FILES')
AS
 COPY INTO {{ cmd_raw }}.CMDI_RAW_TB_TRADES (
 TRADE_DATE, SETTLEMENT_DATE, TRADE_ID, CUSTOMER_ID, ACCOUNT_ID, ORDER_ID,
 COMMODITY_TYPE, COMMODITY_NAME, COMMODITY_CODE, CONTRACT_TYPE, SIDE, QUANTITY, UNIT, PRICE, CURRENCY,
 GROSS_AMOUNT, COMMISSION, NET_AMOUNT, BASE_CURRENCY, BASE_GROSS_AMOUNT, BASE_NET_AMOUNT, FX_RATE,
 CONTRACT_SIZE, NUM_CONTRACTS, DELIVERY_MONTH, DELIVERY_LOCATION, DELTA, VEGA, SPOT_PRICE, FORWARD_PRICE, VOLATILITY,
 EXCHANGE, BROKER_ID, VENUE, LIQUIDITY_SCORE
 )
 FROM @CMDI_RAW_ST_TRADES
 PATTERN = '.*commodity_trades.*\.csv'
 FILE_FORMAT = CMDI_RAW_FF_TRADES_CSV
 ON_ERROR = CONTINUE;

DEFINE TASK {{ db }}.{{ cmd_raw }}.CMDI_RAW_TK_CLEANUP_AFTER_LOAD_TRADES
 USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
 COMMENT = 'Automated stage cleanup AFTER commodity trade data load. Keeps last 5 files to manage storage costs.'
 AFTER {{ db }}.{{ cmd_raw }}.CMDI_RAW_TK_LOAD_TRADES
AS
 CALL CMDI_RAW_SP_CLEANUP_STAGE_KEEP_LAST_N('CMDI_RAW_ST_TRADES', 5);
