/*
 * 302_CRMA_analytics.sql
 * CRM analytics: customer aggregation, sanctions screening
 */
DEFINE VIEW {{ db }}.{{ crm_agg }}.CRMA_AGG_VW_SANCTIONS_ENRICHED AS
SELECT 
    "Sr No.",
    ENTITY_ID,
    ENTITY_NAME,
    ENTITY_ALIASES,
    ENTITY_TYPE,
    TRY_CAST(DOB AS VARCHAR) AS DOB, 
    POB,
    NATIONALITY_COUNTRY,
    CITIZENSHIP_COUNTRY,
    ADDRESS,
    AUTHORITY,
    LIST_NAME,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    ENTITY_NOTES,
    CITATION_LINK,
    COUNTRY,
    LISTING_COUNTRY,
    CALL_SIGN,
    VESSEL_TYPE,
    VESSEL_FLAG,
    VESSEL_OWNER,
    GROSS_TONNAGE,
    GROSS_REGISTERED_TONNAGE,
    CREATED_DATE,

    CASE 
        WHEN AUTHORITY = 'DOT - Department of Treasury' AND LIST_NAME LIKE '%SDN%' THEN 10 
        WHEN AUTHORITY LIKE '%UK%' OR AUTHORITY LIKE '%Canada%' THEN 7                     
        WHEN ENTITY_TYPE = 'Individual' THEN 8                                              
        WHEN ENTITY_TYPE = 'Vessel' THEN 5                                                 
        ELSE 6                                                                              
    END AS RISK_SCORE,

    CASE 
        WHEN EXPIRY_DATE IS NULL THEN TRUE                    
        WHEN EXPIRY_DATE > CURRENT_DATE() THEN TRUE           
        ELSE FALSE                                            
    END AS IS_ACTIVE,

    CASE 
        WHEN LIST_NAME LIKE '%SDN%' THEN 'OFAC Specially Designated Nationals (SDN)'
        WHEN LIST_NAME LIKE '%UK Sanctions%' THEN 'UK Russia Sanctions'
        WHEN LIST_NAME LIKE '%Canada%' THEN 'Canada Port State Control'
        ELSE LIST_NAME
    END AS SANCTIONS_PROGRAM,

    CASE 
        WHEN AUTHORITY LIKE '%DOT%' OR AUTHORITY LIKE '%Treasury%' THEN 'US_OFAC'
        WHEN AUTHORITY LIKE '%UK%' OR AUTHORITY LIKE '%FCDO%' THEN 'UK_OFSI'
        WHEN AUTHORITY LIKE '%Canada%' THEN 'CANADA_PSC'
        WHEN AUTHORITY LIKE '%EU%' THEN 'EU_SANCTIONS'
        WHEN AUTHORITY LIKE '%SECO%' THEN 'SWISS_SECO'
        ELSE 'OTHER'
    END AS AUTHORITY_CATEGORY,

    DATEDIFF(day, EFFECTIVE_DATE, CURRENT_DATE()) AS DAYS_SINCE_LISTING,

    CASE 
        WHEN EXPIRY_DATE IS NOT NULL 
        THEN DATEDIFF(day, CURRENT_DATE(), EXPIRY_DATE)
        ELSE NULL
    END AS DAYS_UNTIL_EXPIRY,

    CURRENT_TIMESTAMP() AS VIEW_CREATED_AT

FROM {{ db }}_REF_DAP_GLOBAL_SANCTIONS_DATA_SET_COPY.PUBLIC.SANCTIONS_TB_DATA_STAGING;

DEFINE VIEW {{ db }}.{{ crm_agg }}.CRMA_AGG_VW_SANCTIONS_CUSTOMER_SCREENING AS
WITH customer_base AS (
    SELECT 
        c.CUSTOMER_ID,
        c.FIRST_NAME,
        c.FAMILY_NAME,
        CONCAT(c.FIRST_NAME, ' ', c.FAMILY_NAME) AS FULL_NAME,
        c.DATE_OF_BIRTH,
        COALESCE(a.COUNTRY, 'UNKNOWN') AS CUSTOMER_COUNTRY,
        NULL AS CUSTOMER_NATIONALITY, 
        NULL AS CUSTOMER_TYPE, 
        c.RISK_CLASSIFICATION,
        c.INSERT_TIMESTAMP_UTC AS CUSTOMER_CREATED_DATE
    FROM {{ db }}.{{ crm_raw }}.CRMI_RAW_TB_CUSTOMER c
    LEFT JOIN (
        SELECT CUSTOMER_ID, COUNTRY, 
               ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY INSERT_TIMESTAMP_UTC DESC) as rn
        FROM {{ db }}.{{ crm_raw }}.CRMI_RAW_TB_ADDRESSES
    ) a ON c.CUSTOMER_ID = a.CUSTOMER_ID AND a.rn = 1
),
exact_matches AS (
    SELECT 
        c.CUSTOMER_ID,
        c.FULL_NAME AS CUSTOMER_NAME,
        c.DATE_OF_BIRTH AS CUSTOMER_DOB,
        c.CUSTOMER_COUNTRY,
        c.CUSTOMER_NATIONALITY,
        c.CUSTOMER_TYPE,
        c.RISK_CLASSIFICATION,
        s.ENTITY_ID,
        s.ENTITY_NAME,
        s.ENTITY_ALIASES,
        s.DOB AS SANCTIONS_DOB,
        s.NATIONALITY_COUNTRY AS SANCTIONS_NATIONALITY,
        s.AUTHORITY,
        s.LIST_NAME,
        s.SANCTIONS_PROGRAM,
        s.RISK_SCORE AS SANCTIONS_RISK_SCORE,
        s.IS_ACTIVE AS SANCTIONS_IS_ACTIVE,
        s.EFFECTIVE_DATE,
        s.EXPIRY_DATE,
        s.CITATION_LINK,
        'EXACT_MATCH' AS MATCH_TYPE,
        100.0 AS MATCH_SCORE,
        0 AS EDIT_DISTANCE
    FROM customer_base c
    INNER JOIN {{ db }}.{{ crm_agg }}.CRMA_AGG_VW_SANCTIONS_ENRICHED s
        ON UPPER(c.FULL_NAME) = UPPER(s.ENTITY_NAME)
    WHERE s.IS_ACTIVE = TRUE 
),
fuzzy_matches AS (
    SELECT 
        c.CUSTOMER_ID,
        c.FULL_NAME AS CUSTOMER_NAME,
        c.DATE_OF_BIRTH AS CUSTOMER_DOB,
        c.CUSTOMER_COUNTRY,
        c.CUSTOMER_NATIONALITY,
        c.CUSTOMER_TYPE,
        c.RISK_CLASSIFICATION,
        s.ENTITY_ID,
        s.ENTITY_NAME,
        s.ENTITY_ALIASES,
        s.DOB AS SANCTIONS_DOB,
        s.NATIONALITY_COUNTRY AS SANCTIONS_NATIONALITY,
        s.AUTHORITY,
        s.LIST_NAME,
        s.SANCTIONS_PROGRAM,
        s.RISK_SCORE AS SANCTIONS_RISK_SCORE,
        s.IS_ACTIVE AS SANCTIONS_IS_ACTIVE,
        s.EFFECTIVE_DATE,
        s.EXPIRY_DATE,
        s.CITATION_LINK,
        'FUZZY_MATCH' AS MATCH_TYPE,
        CASE 
            WHEN EDITDISTANCE(UPPER(c.FULL_NAME), UPPER(s.ENTITY_NAME)) <= 1 THEN 95.0 
            WHEN EDITDISTANCE(UPPER(c.FULL_NAME), UPPER(s.ENTITY_NAME)) <= 2 THEN 90.0 
            WHEN EDITDISTANCE(UPPER(c.FULL_NAME), UPPER(s.ENTITY_NAME)) <= 3 THEN 85.0 
            WHEN EDITDISTANCE(UPPER(c.FULL_NAME), UPPER(s.ENTITY_NAME)) <= 4 THEN 80.0 
            WHEN EDITDISTANCE(UPPER(c.FULL_NAME), UPPER(s.ENTITY_NAME)) <= 5 THEN 75.0 
            ELSE 70.0
        END AS MATCH_SCORE,
        EDITDISTANCE(UPPER(c.FULL_NAME), UPPER(s.ENTITY_NAME)) AS EDIT_DISTANCE
    FROM customer_base c
    INNER JOIN {{ db }}.{{ crm_agg }}.CRMA_AGG_VW_SANCTIONS_ENRICHED s
        ON s.ENTITY_ID NOT IN (
            SELECT ENTITY_ID FROM exact_matches WHERE CUSTOMER_ID = c.CUSTOMER_ID
        )
        AND EDITDISTANCE(UPPER(c.FULL_NAME), UPPER(s.ENTITY_NAME)) <= 5
    WHERE s.IS_ACTIVE = TRUE 
),
alias_matches AS (
    SELECT 
        c.CUSTOMER_ID,
        c.FULL_NAME AS CUSTOMER_NAME,
        c.DATE_OF_BIRTH AS CUSTOMER_DOB,
        c.CUSTOMER_COUNTRY,
        c.CUSTOMER_NATIONALITY,
        c.CUSTOMER_TYPE,
        c.RISK_CLASSIFICATION,
        s.ENTITY_ID,
        s.ENTITY_NAME,
        s.ENTITY_ALIASES,
        s.DOB AS SANCTIONS_DOB,
        s.NATIONALITY_COUNTRY AS SANCTIONS_NATIONALITY,
        s.AUTHORITY,
        s.LIST_NAME,
        s.SANCTIONS_PROGRAM,
        s.RISK_SCORE AS SANCTIONS_RISK_SCORE,
        s.IS_ACTIVE AS SANCTIONS_IS_ACTIVE,
        s.EFFECTIVE_DATE,
        s.EXPIRY_DATE,
        s.CITATION_LINK,
        'ALIAS_MATCH' AS MATCH_TYPE,
        95.0 AS MATCH_SCORE, 
        0 AS EDIT_DISTANCE
    FROM customer_base c
    INNER JOIN {{ db }}.{{ crm_agg }}.CRMA_AGG_VW_SANCTIONS_ENRICHED s
        ON UPPER(s.ENTITY_ALIASES) LIKE '%' || UPPER(c.FULL_NAME) || '%'
        AND s.ENTITY_ID NOT IN (
            SELECT ENTITY_ID FROM exact_matches WHERE CUSTOMER_ID = c.CUSTOMER_ID
        )
    WHERE s.IS_ACTIVE = TRUE
      AND s.ENTITY_ALIASES IS NOT NULL
),
all_matches AS (
    SELECT * FROM exact_matches
    UNION ALL
    SELECT * FROM fuzzy_matches
    UNION ALL
    SELECT * FROM alias_matches
)
SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_DOB,
    CUSTOMER_COUNTRY,
    CUSTOMER_NATIONALITY,
    CUSTOMER_TYPE,
    RISK_CLASSIFICATION,

    ENTITY_ID,
    ENTITY_NAME,
    ENTITY_ALIASES,
    SANCTIONS_DOB,
    SANCTIONS_NATIONALITY,
    AUTHORITY,
    LIST_NAME,
    SANCTIONS_PROGRAM,
    SANCTIONS_RISK_SCORE,
    SANCTIONS_IS_ACTIVE,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    CITATION_LINK,

    MATCH_TYPE,
    MATCH_SCORE,
    EDIT_DISTANCE,

    CASE 
        WHEN CUSTOMER_DOB IS NOT NULL 
             AND SANCTIONS_DOB IS NOT NULL 
             AND SANCTIONS_DOB NOT LIKE '%[%' 
             AND TO_VARCHAR(CUSTOMER_DOB, 'YYYY-MM-DD') = SANCTIONS_DOB 
        THEN TRUE 
        ELSE FALSE 
    END AS DOB_MATCH,
    CASE WHEN CUSTOMER_NATIONALITY = SANCTIONS_NATIONALITY THEN TRUE ELSE FALSE END AS NATIONALITY_MATCH,
    CASE WHEN CUSTOMER_COUNTRY = SANCTIONS_NATIONALITY THEN TRUE ELSE FALSE END AS COUNTRY_MATCH,

    CASE 
        WHEN MATCH_TYPE = 'EXACT_MATCH' THEN 'EXACT'
        WHEN MATCH_TYPE = 'ALIAS_MATCH' THEN 'HIGH_CONFIDENCE'
        WHEN MATCH_SCORE >= 90 THEN 'HIGH_CONFIDENCE'
        WHEN MATCH_SCORE >= 80 THEN 'MEDIUM_CONFIDENCE'
        WHEN MATCH_SCORE >= 70 THEN 'LOW_CONFIDENCE'
        ELSE 'VERY_LOW_CONFIDENCE'
    END AS MATCH_CONFIDENCE,

    CASE 
        WHEN MATCH_TYPE = 'EXACT_MATCH' AND DOB_MATCH THEN 'HARD_BLOCK'
        WHEN MATCH_TYPE = 'EXACT_MATCH' THEN 'IMMEDIATE_INVESTIGATION'
        WHEN MATCH_TYPE = 'ALIAS_MATCH' THEN 'IMMEDIATE_INVESTIGATION'
        WHEN MATCH_SCORE >= 90 AND (DOB_MATCH OR NATIONALITY_MATCH) THEN 'IMMEDIATE_INVESTIGATION'
        WHEN MATCH_SCORE >= 85 THEN 'ENHANCED_DUE_DILIGENCE'
        WHEN MATCH_SCORE >= 75 THEN 'MANUAL_REVIEW'
        ELSE 'LIKELY_FALSE_POSITIVE'
    END AS DISPOSITION_RECOMMENDATION,

    CASE 
        WHEN RISK_CLASSIFICATION = 'CRITICAL' THEN 10
        WHEN RISK_CLASSIFICATION = 'HIGH' THEN 8
        WHEN RISK_CLASSIFICATION = 'MEDIUM' THEN 5
        WHEN RISK_CLASSIFICATION = 'LOW' THEN 3
        ELSE 5
    END + SANCTIONS_RISK_SCORE AS COMBINED_RISK_SCORE,

    CASE 
        WHEN MATCH_TYPE = 'EXACT_MATCH' AND DOB_MATCH THEN 'CRITICAL'
        WHEN MATCH_TYPE = 'EXACT_MATCH' OR MATCH_TYPE = 'ALIAS_MATCH' THEN 'HIGH'
        WHEN MATCH_SCORE >= 85 THEN 'HIGH'
        WHEN MATCH_SCORE >= 75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS ALERT_PRIORITY,

    CURRENT_TIMESTAMP() AS SCREENING_TIMESTAMP

FROM all_matches;

DEFINE VIEW {{ db }}.{{ crm_agg }}.CRMA_AGG_VW_SANCTIONS_SCREENING_SUMMARY AS
SELECT 
    COUNT(DISTINCT CUSTOMER_ID) AS total_customers_with_matches,
    COUNT(DISTINCT ENTITY_ID) AS total_sanctions_entities_matched,
    COUNT(*) AS total_matches,

    COUNT(DISTINCT CASE WHEN MATCH_TYPE = 'EXACT_MATCH' THEN CUSTOMER_ID END) AS exact_match_customers,
    COUNT(DISTINCT CASE WHEN MATCH_TYPE = 'FUZZY_MATCH' THEN CUSTOMER_ID END) AS fuzzy_match_customers,
    COUNT(DISTINCT CASE WHEN MATCH_TYPE = 'ALIAS_MATCH' THEN CUSTOMER_ID END) AS alias_match_customers,

    COUNT(DISTINCT CASE WHEN MATCH_CONFIDENCE = 'EXACT' THEN CUSTOMER_ID END) AS exact_confidence_customers,
    COUNT(DISTINCT CASE WHEN MATCH_CONFIDENCE = 'HIGH_CONFIDENCE' THEN CUSTOMER_ID END) AS high_confidence_customers,
    COUNT(DISTINCT CASE WHEN MATCH_CONFIDENCE = 'MEDIUM_CONFIDENCE' THEN CUSTOMER_ID END) AS medium_confidence_customers,
    COUNT(DISTINCT CASE WHEN MATCH_CONFIDENCE = 'LOW_CONFIDENCE' THEN CUSTOMER_ID END) AS low_confidence_customers,

    COUNT(DISTINCT CASE WHEN DISPOSITION_RECOMMENDATION = 'HARD_BLOCK' THEN CUSTOMER_ID END) AS hard_block_required,
    COUNT(DISTINCT CASE WHEN DISPOSITION_RECOMMENDATION = 'IMMEDIATE_INVESTIGATION' THEN CUSTOMER_ID END) AS immediate_investigation_required,
    COUNT(DISTINCT CASE WHEN DISPOSITION_RECOMMENDATION = 'ENHANCED_DUE_DILIGENCE' THEN CUSTOMER_ID END) AS edd_required,
    COUNT(DISTINCT CASE WHEN DISPOSITION_RECOMMENDATION = 'MANUAL_REVIEW' THEN CUSTOMER_ID END) AS manual_review_required,
    COUNT(DISTINCT CASE WHEN DISPOSITION_RECOMMENDATION = 'LIKELY_FALSE_POSITIVE' THEN CUSTOMER_ID END) AS likely_false_positives,

    COUNT(DISTINCT CASE WHEN ALERT_PRIORITY = 'CRITICAL' THEN CUSTOMER_ID END) AS critical_alerts,
    COUNT(DISTINCT CASE WHEN ALERT_PRIORITY = 'HIGH' THEN CUSTOMER_ID END) AS high_alerts,
    COUNT(DISTINCT CASE WHEN ALERT_PRIORITY = 'MEDIUM' THEN CUSTOMER_ID END) AS medium_alerts,
    COUNT(DISTINCT CASE WHEN ALERT_PRIORITY = 'LOW' THEN CUSTOMER_ID END) AS low_alerts,

    COUNT(DISTINCT CASE WHEN AUTHORITY LIKE '%DOT%' OR AUTHORITY LIKE '%Treasury%' THEN CUSTOMER_ID END) AS ofac_matches,
    COUNT(DISTINCT CASE WHEN AUTHORITY LIKE '%UK%' THEN CUSTOMER_ID END) AS uk_matches,
    COUNT(DISTINCT CASE WHEN AUTHORITY LIKE '%Canada%' THEN CUSTOMER_ID END) AS canada_matches,

    ROUND(AVG(MATCH_SCORE), 2) AS avg_match_score,
    ROUND(AVG(CASE WHEN MATCH_TYPE = 'FUZZY_MATCH' THEN MATCH_SCORE END), 2) AS avg_fuzzy_match_score,

    CURRENT_TIMESTAMP() AS SUMMARY_GENERATED_AT

FROM {{ db }}.{{ crm_agg }}.CRMA_AGG_VW_SANCTIONS_CUSTOMER_SCREENING;

DEFINE VIEW {{ db }}.{{ crm_agg }}.CRMA_AGG_VW_SANCTIONS_HIGH_RISK_ALERTS AS
SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_DOB,
    CUSTOMER_COUNTRY,
    CUSTOMER_NATIONALITY,
    CUSTOMER_TYPE,
    RISK_CLASSIFICATION,
    ENTITY_ID,
    ENTITY_NAME,
    ENTITY_ALIASES,
    SANCTIONS_DOB,
    SANCTIONS_NATIONALITY,
    AUTHORITY,
    LIST_NAME,
    SANCTIONS_PROGRAM,
    SANCTIONS_RISK_SCORE,
    EFFECTIVE_DATE,
    CITATION_LINK,
    MATCH_TYPE,
    MATCH_SCORE,
    EDIT_DISTANCE,
    DOB_MATCH,
    NATIONALITY_MATCH,
    MATCH_CONFIDENCE,
    DISPOSITION_RECOMMENDATION,
    COMBINED_RISK_SCORE,
    ALERT_PRIORITY,
    SCREENING_TIMESTAMP
FROM {{ db }}.{{ crm_agg }}.CRMA_AGG_VW_SANCTIONS_CUSTOMER_SCREENING
WHERE 
    DISPOSITION_RECOMMENDATION IN ('HARD_BLOCK', 'IMMEDIATE_INVESTIGATION', 'ENHANCED_DUE_DILIGENCE')
    AND ALERT_PRIORITY IN ('CRITICAL', 'HIGH')
ORDER BY 
    CASE ALERT_PRIORITY 
        WHEN 'CRITICAL' THEN 1 
        WHEN 'HIGH' THEN 2 
        ELSE 3 
    END,
    COMBINED_RISK_SCORE DESC,
    MATCH_SCORE DESC;
