DEFINE DYNAMIC TABLE {{ db }}.{{ crm_agg }}.ACCA_AGG_DT_ACCOUNTS(
 ACCOUNT_ID VARCHAR(30),
 ACCOUNT_TYPE VARCHAR(20),
 BASE_CURRENCY VARCHAR(3),
 CUSTOMER_ID VARCHAR(30),
 STATUS VARCHAR(20),
 IS_ACTIVE BOOLEAN,
 IS_CHECKING_ACCOUNT BOOLEAN,
 IS_SAVINGS_ACCOUNT BOOLEAN,
 IS_BUSINESS_ACCOUNT BOOLEAN,
 IS_INVESTMENT_ACCOUNT BOOLEAN,
 IS_USD_ACCOUNT BOOLEAN,
 IS_EUR_ACCOUNT BOOLEAN,
 IS_OTHER_CURRENCY_ACCOUNT BOOLEAN,
 ACCOUNT_TYPE_PRIORITY NUMBER(2,0),
 CURRENCY_GROUP VARCHAR(20),
 AGGREGATION_TIMESTAMP TIMESTAMP_NTZ,
 AGGREGATION_TYPE VARCHAR(20),
 SOURCE_TABLE VARCHAR(50)
) COMMENT = '1:1 aggregation of account master data from raw layer (CRM_RAW_001.ACCI_RAW_TB_ACCOUNTS). Provides clean aggregation layer access for downstream analytics, balance calculations, and reporting. Maintains real-time refresh for data currency while serving as bridge between raw data and analytical data products.'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 ACCOUNT_ID,
 ACCOUNT_TYPE,
 BASE_CURRENCY,
 CUSTOMER_ID,
 STATUS,

 CASE
 WHEN STATUS = 'ACTIVE' THEN TRUE
 ELSE FALSE
 END AS IS_ACTIVE,

 CASE
 WHEN ACCOUNT_TYPE = 'CHECKING' THEN TRUE
 ELSE FALSE
 END AS IS_CHECKING_ACCOUNT,

 CASE
 WHEN ACCOUNT_TYPE = 'SAVINGS' THEN TRUE
 ELSE FALSE
 END AS IS_SAVINGS_ACCOUNT,

 CASE
 WHEN ACCOUNT_TYPE = 'BUSINESS' THEN TRUE
 ELSE FALSE
 END AS IS_BUSINESS_ACCOUNT,

 CASE
 WHEN ACCOUNT_TYPE = 'INVESTMENT' THEN TRUE
 ELSE FALSE
 END AS IS_INVESTMENT_ACCOUNT,

 CASE
 WHEN BASE_CURRENCY = 'USD' THEN TRUE
 ELSE FALSE
 END AS IS_USD_ACCOUNT,

 CASE
 WHEN BASE_CURRENCY = 'EUR' THEN TRUE
 ELSE FALSE
 END AS IS_EUR_ACCOUNT,

 CASE
 WHEN BASE_CURRENCY IN ('GBP', 'CHF', 'NOK', 'SEK', 'DKK') THEN TRUE
 ELSE FALSE
 END AS IS_OTHER_CURRENCY_ACCOUNT,

 CASE
 WHEN ACCOUNT_TYPE = 'CHECKING' THEN 1
 WHEN ACCOUNT_TYPE = 'SAVINGS' THEN 2
 WHEN ACCOUNT_TYPE = 'BUSINESS' THEN 3
 WHEN ACCOUNT_TYPE = 'INVESTMENT' THEN 4
 ELSE 99
 END AS ACCOUNT_TYPE_PRIORITY,

 CASE
 WHEN BASE_CURRENCY IN ('EUR', 'GBP') THEN 'MAJOR_EUROPEAN'
 WHEN BASE_CURRENCY = 'USD' THEN 'USD_BASE'
 WHEN BASE_CURRENCY IN ('CHF', 'NOK', 'SEK', 'DKK') THEN 'OTHER_EUROPEAN'
 ELSE 'OTHER'
 END AS CURRENCY_GROUP,

 CURRENT_TIMESTAMP() AS AGGREGATION_TIMESTAMP,
 '1:1_COPY_FROM_RAW' AS AGGREGATION_TYPE,
 'CRM_RAW_001.ACCI_RAW_TB_ACCOUNTS' AS SOURCE_TABLE

FROM {{ crm_raw }}.ACCI_RAW_TB_ACCOUNTS
WHERE 1=1
ORDER BY CUSTOMER_ID, ACCOUNT_TYPE_PRIORITY, ACCOUNT_ID;
