DEFINE DYNAMIC TABLE {{ db }}.{{ ref_agg }}.REFA_AGG_DT_FX_RATES_ENHANCED(
 DATE DATE,
 FROM_CURRENCY VARCHAR(3),
 TO_CURRENCY VARCHAR(3),
 CURRENCY_PAIR VARCHAR(7),
 MID_RATE NUMBER(15,6),
 BID_RATE NUMBER(15,6),
 ASK_RATE NUMBER(15,6),
 SPREAD_ABSOLUTE NUMBER(15,6),
 SPREAD_PERCENTAGE NUMBER(8,4),
 DAILY_CHANGE_ABSOLUTE NUMBER(15,6),
 DAILY_CHANGE_PERCENTAGE NUMBER(8,4),
 TREND_DIRECTION VARCHAR(15),
 VOLATILITY_30D NUMBER(15,6),
 MOVING_AVG_7D NUMBER(15,6),
 MIN_RATE_30D NUMBER(15,6),
 MAX_RATE_30D NUMBER(15,6),
 RATE_POSITION_PERCENTAGE NUMBER(5,2),
 CURRENCY_PAIR_TYPE VARCHAR(15),
 PAIR_CLASSIFICATION VARCHAR(15),
 SPREAD_RISK_LEVEL VARCHAR(20),
 VOLATILITY_RISK_LEVEL VARCHAR(20),
 IS_CURRENT_RATE BOOLEAN,
 CREATED_AT TIMESTAMP_NTZ,
 AGGREGATION_TIMESTAMP TIMESTAMP_NTZ,
 AGGREGATION_TYPE VARCHAR(25)
) COMMENT = 'Enhanced FX rates aggregation with analytics, volatility metrics, and business intelligence. Provides current rates, historical trends, bid/ask spreads, and currency pair analytics for real-time operations, risk management, and regulatory reporting.'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
WITH fx_rates_base AS (
 SELECT
 DATE,
 FROM_CURRENCY,
 TO_CURRENCY,
 MID_RATE,
 BID_RATE,
 ASK_RATE,

 (ASK_RATE - BID_RATE) AS SPREAD_ABSOLUTE,
 CASE
 WHEN MID_RATE > 0 THEN ROUND(((ASK_RATE - BID_RATE) / MID_RATE) * 100, 4)
 ELSE NULL
 END AS SPREAD_PERCENTAGE,

 CASE
 WHEN FROM_CURRENCY = 'CHF' THEN 'CHF_BASE'
 WHEN TO_CURRENCY = 'CHF' THEN 'CHF_TARGET'
 ELSE 'CROSS_CURRENCY'
 END AS CURRENCY_PAIR_TYPE,

 CASE
 WHEN (FROM_CURRENCY IN ('CHF', 'USD', 'EUR', 'GBP') AND TO_CURRENCY IN ('CHF', 'USD', 'EUR', 'GBP'))
 THEN 'MAJOR_PAIR'
 ELSE 'MINOR_PAIR'
 END AS PAIR_CLASSIFICATION,

 LAG(MID_RATE) OVER (PARTITION BY FROM_CURRENCY, TO_CURRENCY ORDER BY DATE) AS PREV_MID_RATE,

 CREATED_AT

 FROM {{ ref_raw }}.REFI_RAW_TB_FX_RATES
),

fx_rates_with_trends AS (
 SELECT
 *,

 CASE
 WHEN PREV_MID_RATE IS NOT NULL AND PREV_MID_RATE > 0
 THEN ROUND(((MID_RATE - PREV_MID_RATE) / PREV_MID_RATE) * 100, 4)
 ELSE NULL
 END AS DAILY_CHANGE_PERCENTAGE,

 CASE
 WHEN PREV_MID_RATE IS NOT NULL
 THEN (MID_RATE - PREV_MID_RATE)
 ELSE NULL
 END AS DAILY_CHANGE_ABSOLUTE,

 CASE
 WHEN PREV_MID_RATE IS NULL THEN 'NO_PREV_DATA'
 WHEN MID_RATE > PREV_MID_RATE THEN 'APPRECIATING'
 WHEN MID_RATE < PREV_MID_RATE THEN 'DEPRECIATING'
 ELSE 'STABLE'
 END AS TREND_DIRECTION,

 STDDEV(MID_RATE) OVER (
 PARTITION BY FROM_CURRENCY, TO_CURRENCY
 ORDER BY DATE
 ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
 ) AS VOLATILITY_30D,

 AVG(MID_RATE) OVER (
 PARTITION BY FROM_CURRENCY, TO_CURRENCY
 ORDER BY DATE
 ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
 ) AS MOVING_AVG_7D,

 MIN(MID_RATE) OVER (
 PARTITION BY FROM_CURRENCY, TO_CURRENCY
 ORDER BY DATE
 ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
 ) AS MIN_RATE_30D,

 MAX(MID_RATE) OVER (
 PARTITION BY FROM_CURRENCY, TO_CURRENCY
 ORDER BY DATE
 ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
 ) AS MAX_RATE_30D

 FROM fx_rates_base
)

SELECT
 DATE,
 FROM_CURRENCY,
 TO_CURRENCY,
 CONCAT(FROM_CURRENCY, '/', TO_CURRENCY) AS CURRENCY_PAIR,
 MID_RATE,
 BID_RATE,
 ASK_RATE,

 SPREAD_ABSOLUTE,
 SPREAD_PERCENTAGE,

 DAILY_CHANGE_ABSOLUTE,
 DAILY_CHANGE_PERCENTAGE,
 TREND_DIRECTION,

 ROUND(VOLATILITY_30D, 6) AS VOLATILITY_30D,
 ROUND(MOVING_AVG_7D, 6) AS MOVING_AVG_7D,
 MIN_RATE_30D,
 MAX_RATE_30D,

 CASE
 WHEN MIN_RATE_30D IS NOT NULL AND MAX_RATE_30D IS NOT NULL AND MAX_RATE_30D > MIN_RATE_30D
 THEN ROUND(((MID_RATE - MIN_RATE_30D) / (MAX_RATE_30D - MIN_RATE_30D)) * 100, 2)
 ELSE NULL
 END AS RATE_POSITION_PERCENTAGE,

 CURRENCY_PAIR_TYPE,
 PAIR_CLASSIFICATION,

 CASE
 WHEN SPREAD_PERCENTAGE IS NULL THEN 'UNKNOWN_SPREAD'
 WHEN SPREAD_PERCENTAGE > 1.0 THEN 'HIGH_SPREAD'
 WHEN SPREAD_PERCENTAGE > 0.5 THEN 'MEDIUM_SPREAD'
 ELSE 'LOW_SPREAD'
 END AS SPREAD_RISK_LEVEL,

 CASE
 WHEN VOLATILITY_30D IS NULL THEN 'UNKNOWN_VOLATILITY'
 WHEN VOLATILITY_30D > 0.05 THEN 'HIGH_VOLATILITY'
 WHEN VOLATILITY_30D > 0.02 THEN 'MEDIUM_VOLATILITY'
 ELSE 'LOW_VOLATILITY'
 END AS VOLATILITY_RISK_LEVEL,

 CASE
 WHEN DATE = CURRENT_DATE() THEN TRUE
 WHEN DATE = (SELECT MAX(DATE) FROM {{ ref_raw }}.REFI_RAW_TB_FX_RATES) THEN TRUE
 ELSE FALSE
 END AS IS_CURRENT_RATE,

 CREATED_AT,
 CURRENT_TIMESTAMP() AS AGGREGATION_TIMESTAMP,
 'ENHANCED_FX_ANALYTICS' AS AGGREGATION_TYPE

FROM fx_rates_with_trends

ORDER BY FROM_CURRENCY, TO_CURRENCY, DATE DESC;
