DEFINE DYNAMIC TABLE {{ db }}.{{ eqt_agg }}.EQTA_AGG_DT_TRADE_SUMMARY(
 TRADE_ID VARCHAR(50),
 TRADE_DATE TIMESTAMP_NTZ,
 SETTLEMENT_DATE DATE,
 CUSTOMER_ID VARCHAR(30),
 ACCOUNT_ID VARCHAR(30),
 ORDER_ID VARCHAR(50),
 EXEC_ID VARCHAR(50),
 SYMBOL VARCHAR(20),
 ISIN VARCHAR(12),
 SIDE CHAR(1),
 SIDE_DESCRIPTION VARCHAR(4),
 QUANTITY NUMBER(15,4),
 PRICE NUMBER(18,4),
 CURRENCY VARCHAR(3),
 GROSS_AMOUNT NUMBER(18,2),
 COMMISSION NUMBER(12,4),
 NET_AMOUNT NUMBER(18,2),
 BASE_CURRENCY VARCHAR(3),
 BASE_GROSS_AMOUNT NUMBER(18,2),
 BASE_NET_AMOUNT NUMBER(18,2),
 FX_RATE NUMBER(15,6),
 MARKET VARCHAR(20),
 ORDER_TYPE VARCHAR(10),
 EXEC_TYPE VARCHAR(15),
 TIME_IN_FORCE VARCHAR(3),
 BROKER_ID VARCHAR(20),
 VENUE VARCHAR(20),
 COMMISSION_RATE_BPS NUMBER(8,2),
 TRADE_VALUE_CATEGORY VARCHAR(10),
 SETTLEMENT_DAYS NUMBER(3,0),
 TRADE_YEAR NUMBER(4,0),
 TRADE_MONTH NUMBER(2,0),
 TRADE_DAY_OF_WEEK NUMBER(1,0),
 CREATED_AT TIMESTAMP_NTZ
) COMMENT = 'Enriched trade-level analytics combining raw FIX protocol data with calculated metrics, classifications, and time dimensions. Provides comprehensive view of all equity trades for execution quality monitoring, broker performance analysis, regulatory reporting (MiFID II), and customer activity tracking. Used by Trading Desk for execution analysis, Risk for exposure monitoring, Compliance for trade surveillance, and Wealth Management for customer reporting. Automatically refreshes hourly as new trades arrive.'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 t.TRADE_ID,
 t.TRADE_DATE,
 t.SETTLEMENT_DATE,
 t.CUSTOMER_ID,
 t.ACCOUNT_ID,
 t.ORDER_ID,
 t.EXEC_ID,

 t.SYMBOL,
 t.ISIN,
 t.SIDE,
 CASE t.SIDE
 WHEN '1' THEN 'BUY'
 WHEN '2' THEN 'SELL'
 ELSE 'UNKNOWN'
 END AS SIDE_DESCRIPTION,

 t.QUANTITY,
 t.PRICE,
 t.CURRENCY,
 t.GROSS_AMOUNT,
 t.COMMISSION,
 t.NET_AMOUNT,

 t.BASE_CURRENCY,
 t.BASE_GROSS_AMOUNT,
 t.BASE_NET_AMOUNT,
 t.FX_RATE,

 t.MARKET,
 t.ORDER_TYPE,
 t.EXEC_TYPE,
 t.TIME_IN_FORCE,
 t.BROKER_ID,
 t.VENUE,

 ROUND(
 CASE
 WHEN ABS(t.GROSS_AMOUNT) > 0 THEN
 (t.COMMISSION / ABS(t.GROSS_AMOUNT)) * 10000
 ELSE 0
 END, 2
 ) AS COMMISSION_RATE_BPS,

 CASE
 WHEN ABS(t.BASE_GROSS_AMOUNT) >= 1000000 THEN 'VERY_LARGE'
 WHEN ABS(t.BASE_GROSS_AMOUNT) >= 100000 THEN 'LARGE'
 WHEN ABS(t.BASE_GROSS_AMOUNT) >= 10000 THEN 'MEDIUM'
 ELSE 'SMALL'
 END AS TRADE_VALUE_CATEGORY,

 DATEDIFF(DAY, t.TRADE_DATE, t.SETTLEMENT_DATE) AS SETTLEMENT_DAYS,

 YEAR(t.TRADE_DATE) AS TRADE_YEAR,
 MONTH(t.TRADE_DATE) AS TRADE_MONTH,
 DAYOFWEEK(t.TRADE_DATE) AS TRADE_DAY_OF_WEEK,

 t.CREATED_AT

FROM {{ eqt_raw }}.EQTI_RAW_TB_TRADES t
ORDER BY t.TRADE_DATE DESC;

DEFINE DYNAMIC TABLE {{ db }}.{{ eqt_agg }}.EQTA_AGG_DT_PORTFOLIO_POSITIONS(
 ACCOUNT_ID VARCHAR(30),
 CUSTOMER_ID VARCHAR(30),
 SYMBOL VARCHAR(20),
 ISIN VARCHAR(12),
 CURRENCY VARCHAR(3),
 TOTAL_QUANTITY NUMBER(15,4),
 TOTAL_BUYS NUMBER(15,4),
 TOTAL_SELLS NUMBER(15,4),
 AVERAGE_BUY_PRICE NUMBER(18,4),
 AVERAGE_SELL_PRICE NUMBER(18,4),
 TOTAL_BUY_AMOUNT NUMBER(18,2),
 TOTAL_SELL_AMOUNT NUMBER(18,2),
 TOTAL_COMMISSION NUMBER(12,4),
 NET_INVESTMENT NUMBER(18,2),
 TOTAL_BUY_AMOUNT_CHF NUMBER(18,2),
 TOTAL_SELL_AMOUNT_CHF NUMBER(18,2),
 NET_INVESTMENT_CHF NUMBER(18,2),
 REALIZED_PL_CHF NUMBER(18,2),
 POSITION_STATUS VARCHAR(10),
 FIRST_TRADE_DATE DATE,
 LAST_TRADE_DATE DATE,
 TRADE_COUNT NUMBER(10,0),
