DEFINE DYNAMIC TABLE {{ db }}.{{ fii_agg }}.FIIA_AGG_DT_TRADE_SUMMARY(
 TRADE_ID VARCHAR(50),
 TRADE_DATE TIMESTAMP_NTZ,
 SETTLEMENT_DATE DATE,
 CUSTOMER_ID VARCHAR(30),
 ACCOUNT_ID VARCHAR(30),
 INSTRUMENT_TYPE VARCHAR(10),
 INSTRUMENT_ID VARCHAR(50),
 ISSUER VARCHAR(100),
 ISSUER_TYPE VARCHAR(20),
 CURRENCY VARCHAR(3),
 SIDE CHAR(1),
 SIDE_DESCRIPTION VARCHAR(12),
 NOTIONAL NUMBER(18,2),
 PRICE NUMBER(18,4),
 GROSS_AMOUNT NUMBER(18,2),
 NET_AMOUNT NUMBER(18,2),
 BASE_GROSS_AMOUNT NUMBER(18,2),
 BASE_NET_AMOUNT NUMBER(18,2),
 FX_RATE NUMBER(15,6),
 DURATION NUMBER(8,4),
 DV01 NUMBER(18,2),
 CREDIT_RATING VARCHAR(3),
 CREDIT_SPREAD_BPS NUMBER(8,2),
 MATURITY_DATE DATE,
 DAYS_TO_MATURITY NUMBER(10,0),
 LIQUIDITY_SCORE NUMBER(2,0),
 TRADE_VALUE_CATEGORY VARCHAR(15),
 MATURITY_BUCKET VARCHAR(15),
 CREATED_AT TIMESTAMP_NTZ
) COMMENT = 'Enriched fixed income trade analytics with risk metrics and classifications'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 t.TRADE_ID,
 t.TRADE_DATE,
 t.SETTLEMENT_DATE,
 t.CUSTOMER_ID,
 t.ACCOUNT_ID,
 t.INSTRUMENT_TYPE,
 t.INSTRUMENT_ID,
 t.ISSUER,
 t.ISSUER_TYPE,
 t.CURRENCY,
 t.SIDE,
 CASE t.SIDE
 WHEN '1' THEN 'BUY/PAY'
 WHEN '2' THEN 'SELL/RECEIVE'
 ELSE 'UNKNOWN'
 END AS SIDE_DESCRIPTION,
 t.NOTIONAL,
 t.PRICE,
 t.GROSS_AMOUNT,
 t.NET_AMOUNT,
 t.BASE_GROSS_AMOUNT,
 t.BASE_NET_AMOUNT,
 t.FX_RATE,
 t.DURATION,
 t.DV01,
 t.CREDIT_RATING,
 t.CREDIT_SPREAD_BPS,
 t.MATURITY_DATE,
 DATEDIFF(DAY, CURRENT_DATE, t.MATURITY_DATE) AS DAYS_TO_MATURITY,
 t.LIQUIDITY_SCORE,

 CASE
 WHEN ABS(t.BASE_GROSS_AMOUNT) >= 10000000 THEN 'VERY_LARGE'
 WHEN ABS(t.BASE_GROSS_AMOUNT) >= 1000000 THEN 'LARGE'
 WHEN ABS(t.BASE_GROSS_AMOUNT) >= 100000 THEN 'MEDIUM'
 ELSE 'SMALL'
 END AS TRADE_VALUE_CATEGORY,

 CASE
 WHEN DATEDIFF(DAY, CURRENT_DATE, t.MATURITY_DATE) <= 365 THEN 'SHORT_TERM'
 WHEN DATEDIFF(DAY, CURRENT_DATE, t.MATURITY_DATE) <= 1825 THEN 'MEDIUM_TERM'
 ELSE 'LONG_TERM'
 END AS MATURITY_BUCKET,

 t.CREATED_AT

FROM {{ fii_raw }}.FIII_RAW_TB_TRADES t
ORDER BY t.TRADE_DATE DESC;

DEFINE DYNAMIC TABLE {{ db }}.{{ fii_agg }}.FIIA_AGG_DT_PORTFOLIO_POSITIONS(
 ACCOUNT_ID VARCHAR(30),
 CUSTOMER_ID VARCHAR(30),
 INSTRUMENT_TYPE VARCHAR(10),
 ISSUER VARCHAR(100),
 ISSUER_TYPE VARCHAR(20),
 CREDIT_RATING VARCHAR(3),
 CURRENCY VARCHAR(3),
 TOTAL_NOTIONAL NUMBER(18,2),
 TOTAL_TRADES NUMBER(10,0),
 TOTAL_BUY_TRADES NUMBER(10,0),
 TOTAL_SELL_TRADES NUMBER(10,0),
 TOTAL_INVESTMENT_CHF NUMBER(18,2),
 NET_INVESTMENT_CHF NUMBER(18,2),
 REALIZED_PL_CHF NUMBER(18,2),
 AVERAGE_DURATION NUMBER(8,4),
 TOTAL_DV01_CHF NUMBER(18,2),
 AVERAGE_CREDIT_SPREAD_BPS NUMBER(8,2),
 POSITION_STATUS VARCHAR(10),
 FIRST_TRADE_DATE DATE,
 LAST_TRADE_DATE DATE,
 LAST_UPDATED TIMESTAMP_NTZ
) COMMENT = 'Current fixed income portfolio positions by customer and issuer'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 t.ACCOUNT_ID,
 t.CUSTOMER_ID,
 t.INSTRUMENT_TYPE,
 t.ISSUER,
 t.ISSUER_TYPE,
 t.CREDIT_RATING,
 t.CURRENCY,

 SUM(CASE WHEN t.SIDE = '1' THEN t.NOTIONAL ELSE -t.NOTIONAL END) AS TOTAL_NOTIONAL,

 COUNT(*) AS TOTAL_TRADES,
 COUNT(CASE WHEN t.SIDE = '1' THEN 1 END) AS TOTAL_BUY_TRADES,
 COUNT(CASE WHEN t.SIDE = '2' THEN 1 END) AS TOTAL_SELL_TRADES,

 SUM(ABS(t.BASE_GROSS_AMOUNT)) AS TOTAL_INVESTMENT_CHF,

 ROUND(SUM(t.BASE_NET_AMOUNT), 2) AS NET_INVESTMENT_CHF,

 ROUND(
 SUM(CASE WHEN t.SIDE = '2' THEN ABS(t.BASE_GROSS_AMOUNT) ELSE 0 END) -
 (
 CASE
 WHEN SUM(CASE WHEN t.SIDE = '2' THEN t.NOTIONAL ELSE 0 END) > 0
 AND SUM(CASE WHEN t.SIDE = '1' THEN t.NOTIONAL ELSE 0 END) > 0 THEN
 (SUM(CASE WHEN t.SIDE = '1' THEN ABS(t.BASE_GROSS_AMOUNT) ELSE 0 END) /
 SUM(CASE WHEN t.SIDE = '1' THEN t.NOTIONAL ELSE 0 END)) *
 SUM(CASE WHEN t.SIDE = '2' THEN t.NOTIONAL ELSE 0 END)
 ELSE 0
 END
 ), 2
 ) AS REALIZED_PL_CHF,

 ROUND(
 SUM(t.DURATION * ABS(t.NOTIONAL)) / NULLIF(SUM(ABS(t.NOTIONAL)), 0), 2
 ) AS AVERAGE_DURATION,

 SUM(t.DV01) AS TOTAL_DV01_CHF,

 ROUND(
 AVG(t.CREDIT_SPREAD_BPS), 2
 ) AS AVERAGE_CREDIT_SPREAD_BPS,

 CASE
 WHEN SUM(CASE WHEN t.SIDE = '1' THEN t.NOTIONAL ELSE -t.NOTIONAL END) > 0 THEN 'LONG'
 WHEN SUM(CASE WHEN t.SIDE = '1' THEN t.NOTIONAL ELSE -t.NOTIONAL END) < 0 THEN 'SHORT'
 ELSE 'CLOSED'
 END AS POSITION_STATUS,

 MIN(t.TRADE_DATE) AS FIRST_TRADE_DATE,
 MAX(t.TRADE_DATE) AS LAST_TRADE_DATE,
 CURRENT_TIMESTAMP() AS LAST_UPDATED

FROM {{ fii_raw }}.FIII_RAW_TB_TRADES t
GROUP BY t.ACCOUNT_ID, t.CUSTOMER_ID, t.INSTRUMENT_TYPE, t.ISSUER, t.ISSUER_TYPE, t.CREDIT_RATING, t.CURRENCY
ORDER BY TOTAL_INVESTMENT_CHF DESC;

DEFINE DYNAMIC TABLE {{ db }}.{{ fii_agg }}.FIIA_AGG_DT_DURATION_ANALYSIS(
 CURRENCY VARCHAR(3),
 MATURITY_BUCKET VARCHAR(15),
 TOTAL_POSITIONS NUMBER(10,0),
 TOTAL_NOTIONAL NUMBER(18,2),
 TOTAL_NOTIONAL_CHF NUMBER(18,2),
 WEIGHTED_AVG_DURATION NUMBER(8,4),
 TOTAL_DV01_CHF NUMBER(18,2),
 MIN_DURATION NUMBER(8,4),
 MAX_DURATION NUMBER(8,4),
 LAST_UPDATED TIMESTAMP_NTZ
) COMMENT = 'Interest rate risk metrics by maturity bucket and currency'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 t.CURRENCY,
 CASE
 WHEN DATEDIFF(DAY, CURRENT_DATE, t.MATURITY_DATE) <= 365 THEN 'SHORT_TERM'
 WHEN DATEDIFF(DAY, CURRENT_DATE, t.MATURITY_DATE) <= 1825 THEN 'MEDIUM_TERM'
 ELSE 'LONG_TERM'
 END AS MATURITY_BUCKET,

 COUNT(*) AS TOTAL_POSITIONS,
 SUM(t.NOTIONAL) AS TOTAL_NOTIONAL,
 SUM(t.BASE_GROSS_AMOUNT) AS TOTAL_NOTIONAL_CHF,

 ROUND(
 SUM(t.DURATION * ABS(t.NOTIONAL)) / NULLIF(SUM(ABS(t.NOTIONAL)), 0), 2
 ) AS WEIGHTED_AVG_DURATION,

 SUM(t.DV01) AS TOTAL_DV01_CHF,
 MIN(t.DURATION) AS MIN_DURATION,
 MAX(t.DURATION) AS MAX_DURATION,
 CURRENT_TIMESTAMP() AS LAST_UPDATED

FROM {{ fii_raw }}.FIII_RAW_TB_TRADES t
WHERE t.INSTRUMENT_TYPE = 'BOND'
GROUP BY t.CURRENCY, MATURITY_BUCKET
ORDER BY t.CURRENCY, MATURITY_BUCKET;

DEFINE DYNAMIC TABLE {{ db }}.{{ fii_agg }}.FIIA_AGG_DT_CREDIT_EXPOSURE(
 CREDIT_RATING VARCHAR(3),
 ISSUER_TYPE VARCHAR(20),
 TOTAL_POSITIONS NUMBER(10,0),
 TOTAL_NOTIONAL_CHF NUMBER(18,2),
 AVERAGE_CREDIT_SPREAD_BPS NUMBER(8,2),
 TOTAL_DV01_CHF NUMBER(18,2),
 CONCENTRATION_PERCENTAGE NUMBER(8,2),
 LAST_UPDATED TIMESTAMP_NTZ
) COMMENT = 'Credit risk exposure by rating and issuer type'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
WITH total_portfolio AS (
 SELECT SUM(ABS(BASE_GROSS_AMOUNT)) AS total_notional
 FROM {{ fii_raw }}.FIII_RAW_TB_TRADES
 WHERE INSTRUMENT_TYPE = 'BOND'
)
SELECT
 t.CREDIT_RATING,
 t.ISSUER_TYPE,
 COUNT(*) AS TOTAL_POSITIONS,
 SUM(ABS(t.BASE_GROSS_AMOUNT)) AS TOTAL_NOTIONAL_CHF,
 ROUND(AVG(t.CREDIT_SPREAD_BPS), 2) AS AVERAGE_CREDIT_SPREAD_BPS,
 SUM(t.DV01) AS TOTAL_DV01_CHF,
 ROUND(
 (SUM(ABS(t.BASE_GROSS_AMOUNT)) / tp.total_notional) * 100, 2
 ) AS CONCENTRATION_PERCENTAGE,
 CURRENT_TIMESTAMP() AS LAST_UPDATED

FROM {{ fii_raw }}.FIII_RAW_TB_TRADES t
CROSS JOIN total_portfolio tp
WHERE t.INSTRUMENT_TYPE = 'BOND'
GROUP BY t.CREDIT_RATING, t.ISSUER_TYPE, tp.total_notional
ORDER BY TOTAL_NOTIONAL_CHF DESC;

DEFINE DYNAMIC TABLE {{ db }}.{{ fii_agg }}.FIIA_AGG_DT_YIELD_CURVE(
 CURRENCY VARCHAR(3),
 MATURITY_YEARS NUMBER(10,0),
 AVERAGE_YIELD NUMBER(8,4),
 AVERAGE_CREDIT_SPREAD_BPS NUMBER(8,2),
 TRADE_COUNT NUMBER(10,0),
 LAST_UPDATED TIMESTAMP_NTZ
) COMMENT = 'Yield curve construction by currency and maturity'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 t.CURRENCY,
 ROUND(DATEDIFF(DAY, CURRENT_DATE, t.MATURITY_DATE) / 365.0, 0) AS MATURITY_YEARS,
 ROUND(AVG(t.COUPON_RATE), 2) AS AVERAGE_YIELD,
 ROUND(AVG(t.CREDIT_SPREAD_BPS), 2) AS AVERAGE_CREDIT_SPREAD_BPS,
 COUNT(*) AS TRADE_COUNT,
 CURRENT_TIMESTAMP() AS LAST_UPDATED

FROM {{ fii_raw }}.FIII_RAW_TB_TRADES t
WHERE t.INSTRUMENT_TYPE = 'BOND'
 AND t.MATURITY_DATE > CURRENT_DATE
GROUP BY t.CURRENCY, MATURITY_YEARS
HAVING TRADE_COUNT >= 3
ORDER BY t.CURRENCY, MATURITY_YEARS;
