DEFINE DYNAMIC TABLE {{ db }}.{{ cmd_agg }}.CMDA_AGG_DT_TRADE_SUMMARY(
 TRADE_ID VARCHAR(50),
 TRADE_DATE TIMESTAMP_NTZ,
 SETTLEMENT_DATE DATE,
 CUSTOMER_ID VARCHAR(30),
 ACCOUNT_ID VARCHAR(30),
 COMMODITY_TYPE VARCHAR(20),
 COMMODITY_NAME VARCHAR(100),
 COMMODITY_CODE VARCHAR(20),
 CONTRACT_TYPE VARCHAR(20),
 SIDE VARCHAR(1),
 SIDE_DESCRIPTION VARCHAR(10),
 QUANTITY DECIMAL(28,4),
 UNIT VARCHAR(20),
 PRICE DECIMAL(28,4),
 CURRENCY VARCHAR(3),
 GROSS_AMOUNT DECIMAL(28,2),
 NET_AMOUNT DECIMAL(28,2),
 BASE_GROSS_AMOUNT DECIMAL(28,2),
 BASE_NET_AMOUNT DECIMAL(28,2),
 FX_RATE DECIMAL(28,6),
 DELTA DECIMAL(28,2),
 SPOT_PRICE DECIMAL(28,4),
 FORWARD_PRICE DECIMAL(28,4),
 VOLATILITY DECIMAL(5,2),
 LIQUIDITY_SCORE NUMBER(2,0),
 EXCHANGE VARCHAR(50),
 DELIVERY_MONTH VARCHAR(7),
 DELIVERY_LOCATION VARCHAR(100),
 TRADE_VALUE_CATEGORY VARCHAR(15),
 VOLATILITY_REGIME VARCHAR(10),
 CREATED_AT TIMESTAMP_NTZ
) COMMENT = 'Enriched commodity trade analytics with risk metrics and classifications'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 t.TRADE_ID,
 t.TRADE_DATE,
 t.SETTLEMENT_DATE,
 t.CUSTOMER_ID,
 t.ACCOUNT_ID,
 t.COMMODITY_TYPE,
 t.COMMODITY_NAME,
 t.COMMODITY_CODE,
 t.CONTRACT_TYPE,
 t.SIDE,
 CASE t.SIDE
 WHEN '1' THEN 'BUY'
 WHEN '2' THEN 'SELL'
 ELSE 'UNKNOWN'
 END AS SIDE_DESCRIPTION,
 t.QUANTITY,
 t.UNIT,
 t.PRICE,
 t.CURRENCY,
 t.GROSS_AMOUNT,
 t.NET_AMOUNT,
 t.BASE_GROSS_AMOUNT,
 t.BASE_NET_AMOUNT,
 t.FX_RATE,
 t.DELTA,
 t.SPOT_PRICE,
 t.FORWARD_PRICE,
 t.VOLATILITY,
 t.LIQUIDITY_SCORE,
 t.EXCHANGE,
 t.DELIVERY_MONTH,
 t.DELIVERY_LOCATION,

 CASE
 WHEN ABS(t.BASE_GROSS_AMOUNT) >= 1000000 THEN 'VERY_LARGE'
 WHEN ABS(t.BASE_GROSS_AMOUNT) >= 100000 THEN 'LARGE'
 WHEN ABS(t.BASE_GROSS_AMOUNT) >= 10000 THEN 'MEDIUM'
 ELSE 'SMALL'
 END AS TRADE_VALUE_CATEGORY,

 CASE
 WHEN t.VOLATILITY >= 50 THEN 'EXTREME'
 WHEN t.VOLATILITY >= 30 THEN 'HIGH'
 WHEN t.VOLATILITY >= 15 THEN 'NORMAL'
 ELSE 'LOW'
 END AS VOLATILITY_REGIME,

 t.CREATED_AT

FROM {{ cmd_raw }}.CMDI_RAW_TB_TRADES t
ORDER BY t.TRADE_DATE DESC;

DEFINE DYNAMIC TABLE {{ db }}.{{ cmd_agg }}.CMDA_AGG_DT_PORTFOLIO_POSITIONS(
 ACCOUNT_ID VARCHAR(30),
 CUSTOMER_ID VARCHAR(30),
 COMMODITY_TYPE VARCHAR(20),
 COMMODITY_NAME VARCHAR(100),
 COMMODITY_CODE VARCHAR(20),
 UNIT VARCHAR(20),
 TOTAL_QUANTITY DECIMAL(28,4),
 TOTAL_BUY_QUANTITY DECIMAL(28,4),
 TOTAL_SELL_QUANTITY DECIMAL(28,4),
 TOTAL_TRADES NUMBER(10,0),
 TOTAL_INVESTMENT_CHF DECIMAL(28,2),
 NET_INVESTMENT_CHF DECIMAL(28,2),
 REALIZED_PL_CHF DECIMAL(28,2),
 AVERAGE_PRICE DECIMAL(28,4),
 TOTAL_DELTA_CHF DECIMAL(28,2),
 AVERAGE_VOLATILITY DECIMAL(5,2),
 POSITION_STATUS VARCHAR(10),
 FIRST_TRADE_DATE TIMESTAMP_NTZ,
 LAST_TRADE_DATE TIMESTAMP_NTZ,
 LAST_UPDATED TIMESTAMP_NTZ
) COMMENT = 'Current commodity portfolio positions by customer and commodity type'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 t.ACCOUNT_ID,
 t.CUSTOMER_ID,
 t.COMMODITY_TYPE,
 t.COMMODITY_NAME,
 t.COMMODITY_CODE,
 t.UNIT,

 SUM(CASE WHEN t.SIDE = '1' THEN t.QUANTITY ELSE -t.QUANTITY END) AS TOTAL_QUANTITY,
 SUM(CASE WHEN t.SIDE = '1' THEN t.QUANTITY ELSE 0 END) AS TOTAL_BUY_QUANTITY,
 SUM(CASE WHEN t.SIDE = '2' THEN t.QUANTITY ELSE 0 END) AS TOTAL_SELL_QUANTITY,

 COUNT(*) AS TOTAL_TRADES,

 SUM(ABS(t.BASE_GROSS_AMOUNT)) AS TOTAL_INVESTMENT_CHF,

 ROUND(SUM(t.BASE_NET_AMOUNT), 2) AS NET_INVESTMENT_CHF,

 ROUND(
 SUM(CASE WHEN t.SIDE = '2' THEN ABS(t.BASE_GROSS_AMOUNT) ELSE 0 END) -
 (
 CASE
 WHEN SUM(CASE WHEN t.SIDE = '2' THEN t.QUANTITY ELSE 0 END) > 0
 AND SUM(CASE WHEN t.SIDE = '1' THEN t.QUANTITY ELSE 0 END) > 0 THEN
 (SUM(CASE WHEN t.SIDE = '1' THEN ABS(t.BASE_GROSS_AMOUNT) ELSE 0 END) /
 SUM(CASE WHEN t.SIDE = '1' THEN t.QUANTITY ELSE 0 END)) *
 SUM(CASE WHEN t.SIDE = '2' THEN t.QUANTITY ELSE 0 END)
 ELSE 0
 END
 ), 2
 ) AS REALIZED_PL_CHF,

 ROUND(
 SUM(t.PRICE * t.QUANTITY) / NULLIF(SUM(t.QUANTITY), 0), 2
 ) AS AVERAGE_PRICE,

 SUM(t.DELTA) AS TOTAL_DELTA_CHF,
 ROUND(AVG(t.VOLATILITY), 2) AS AVERAGE_VOLATILITY,

 CASE
 WHEN SUM(CASE WHEN t.SIDE = '1' THEN t.QUANTITY ELSE -t.QUANTITY END) > 0 THEN 'LONG'
 WHEN SUM(CASE WHEN t.SIDE = '1' THEN t.QUANTITY ELSE -t.QUANTITY END) < 0 THEN 'SHORT'
 ELSE 'CLOSED'
 END AS POSITION_STATUS,

 MIN(t.TRADE_DATE) AS FIRST_TRADE_DATE,
 MAX(t.TRADE_DATE) AS LAST_TRADE_DATE,
 CURRENT_TIMESTAMP() AS LAST_UPDATED

FROM {{ cmd_raw }}.CMDI_RAW_TB_TRADES t
GROUP BY t.ACCOUNT_ID, t.CUSTOMER_ID, t.COMMODITY_TYPE, t.COMMODITY_NAME, t.COMMODITY_CODE, t.UNIT
ORDER BY TOTAL_INVESTMENT_CHF DESC;

DEFINE DYNAMIC TABLE {{ db }}.{{ cmd_agg }}.CMDA_AGG_DT_DELTA_EXPOSURE(
 COMMODITY_TYPE VARCHAR(20),
 TOTAL_POSITIONS NUMBER(10,0),
 LONG_POSITIONS NUMBER(10,0),
 SHORT_POSITIONS NUMBER(10,0),
 TOTAL_DELTA_CHF DECIMAL(28,2),
 LONG_DELTA_CHF DECIMAL(28,2),
 SHORT_DELTA_CHF DECIMAL(28,2),
 NET_DELTA_CHF DECIMAL(28,2),
 LARGEST_SINGLE_POSITION_CHF DECIMAL(28,2),
 CONCENTRATION_PERCENTAGE DECIMAL(5,2),
 LAST_UPDATED TIMESTAMP_NTZ
) COMMENT = 'Delta exposure by commodity class for price risk management'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
WITH total_portfolio AS (
 SELECT SUM(ABS(BASE_GROSS_AMOUNT)) AS total_value
 FROM {{ cmd_raw }}.CMDI_RAW_TB_TRADES
)
SELECT
 t.COMMODITY_TYPE,
 COUNT(*) AS TOTAL_POSITIONS,
 COUNT(CASE WHEN t.SIDE = '1' THEN 1 END) AS LONG_POSITIONS,
 COUNT(CASE WHEN t.SIDE = '2' THEN 1 END) AS SHORT_POSITIONS,

 SUM(ABS(t.DELTA)) AS TOTAL_DELTA_CHF,
 SUM(CASE WHEN t.SIDE = '1' THEN ABS(t.DELTA) ELSE 0 END) AS LONG_DELTA_CHF,
 SUM(CASE WHEN t.SIDE = '2' THEN ABS(t.DELTA) ELSE 0 END) AS SHORT_DELTA_CHF,
 SUM(CASE WHEN t.SIDE = '1' THEN t.DELTA ELSE -t.DELTA END) AS NET_DELTA_CHF,

 MAX(ABS(t.BASE_GROSS_AMOUNT)) AS LARGEST_SINGLE_POSITION_CHF,

 ROUND(
 (SUM(ABS(t.BASE_GROSS_AMOUNT)) / tp.total_value) * 100, 2
 ) AS CONCENTRATION_PERCENTAGE,

 CURRENT_TIMESTAMP() AS LAST_UPDATED

FROM {{ cmd_raw }}.CMDI_RAW_TB_TRADES t
CROSS JOIN total_portfolio tp
GROUP BY t.COMMODITY_TYPE, tp.total_value
ORDER BY TOTAL_DELTA_CHF DESC;

DEFINE DYNAMIC TABLE {{ db }}.{{ cmd_agg }}.CMDA_AGG_DT_VOLATILITY_ANALYSIS(
 COMMODITY_NAME VARCHAR(100),
 COMMODITY_TYPE VARCHAR(20),
 CURRENT_VOLATILITY DECIMAL(5,2),
 MIN_VOLATILITY DECIMAL(5,2),
 MAX_VOLATILITY DECIMAL(5,2),
 VOLATILITY_REGIME VARCHAR(10),
 TRADE_COUNT NUMBER(10,0),
 TOTAL_VALUE_CHF DECIMAL(28,2),
 LAST_UPDATED TIMESTAMP_NTZ
) COMMENT = 'Volatility analysis by commodity for risk assessment'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 t.COMMODITY_NAME,
 t.COMMODITY_TYPE,
 ROUND(AVG(t.VOLATILITY), 2) AS CURRENT_VOLATILITY,
 ROUND(MIN(t.VOLATILITY), 2) AS MIN_VOLATILITY,
 ROUND(MAX(t.VOLATILITY), 2) AS MAX_VOLATILITY,

 CASE
 WHEN AVG(t.VOLATILITY) >= 50 THEN 'EXTREME'
 WHEN AVG(t.VOLATILITY) >= 30 THEN 'HIGH'
 WHEN AVG(t.VOLATILITY) >= 15 THEN 'NORMAL'
 ELSE 'LOW'
 END AS VOLATILITY_REGIME,

 COUNT(*) AS TRADE_COUNT,
 SUM(ABS(t.BASE_GROSS_AMOUNT)) AS TOTAL_VALUE_CHF,
 CURRENT_TIMESTAMP() AS LAST_UPDATED

FROM {{ cmd_raw }}.CMDI_RAW_TB_TRADES t
GROUP BY t.COMMODITY_NAME, t.COMMODITY_TYPE
ORDER BY CURRENT_VOLATILITY DESC;

DEFINE DYNAMIC TABLE {{ db }}.{{ cmd_agg }}.CMDA_AGG_DT_DELIVERY_SCHEDULE(
 DELIVERY_MONTH VARCHAR(7),
 DELIVERY_LOCATION VARCHAR(100),
 COMMODITY_TYPE VARCHAR(20),
 COMMODITY_NAME VARCHAR(100),
 TOTAL_QUANTITY_TO_DELIVER DECIMAL(28,4),
 TOTAL_QUANTITY_TO_RECEIVE DECIMAL(28,4),
 NET_DELIVERY_OBLIGATION DECIMAL(28,4),
 UNIT VARCHAR(20),
 CONTRACT_COUNT NUMBER(10,0),
 EARLIEST_TRADE_DATE TIMESTAMP_NTZ,
 LAST_UPDATED TIMESTAMP_NTZ
) COMMENT = 'Physical delivery schedule and logistics tracking'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 t.DELIVERY_MONTH,
 t.DELIVERY_LOCATION,
 t.COMMODITY_TYPE,
 t.COMMODITY_NAME,

 SUM(CASE WHEN t.SIDE = '2' THEN t.QUANTITY ELSE 0 END) AS TOTAL_QUANTITY_TO_DELIVER,
 SUM(CASE WHEN t.SIDE = '1' THEN t.QUANTITY ELSE 0 END) AS TOTAL_QUANTITY_TO_RECEIVE,
 SUM(CASE WHEN t.SIDE = '1' THEN t.QUANTITY ELSE -t.QUANTITY END) AS NET_DELIVERY_OBLIGATION,

 t.UNIT,
 COUNT(*) AS CONTRACT_COUNT,
 MIN(t.TRADE_DATE) AS EARLIEST_TRADE_DATE,
 CURRENT_TIMESTAMP() AS LAST_UPDATED

FROM {{ cmd_raw }}.CMDI_RAW_TB_TRADES t
WHERE t.DELIVERY_MONTH IS NOT NULL
 AND t.CONTRACT_TYPE IN ('FUTURE', 'FORWARD')
GROUP BY t.DELIVERY_MONTH, t.DELIVERY_LOCATION, t.COMMODITY_TYPE, t.COMMODITY_NAME, t.UNIT
ORDER BY t.DELIVERY_MONTH, t.COMMODITY_TYPE;
