DEFINE DYNAMIC TABLE {{ db }}.{{ rep_agg }}.REPP_AGG_DT_LCR_HQLA(
 AS_OF_DATE DATE,
 HQLA_LEVEL VARCHAR(10),
 ASSET_TYPE VARCHAR(50),
 HOLDINGS_COUNT NUMBER(10,0),
 COUNTERPARTY_TYPE VARCHAR(50),
 ACCOUNT_COUNT NUMBER(10,0),
 L1_TOTAL NUMBER(18,2),
 L2A_TOTAL NUMBER(18,2),
 L2B_TOTAL NUMBER(18,2),
 L2_UNCAPPED NUMBER(18,2),
 L2_CAPPED NUMBER(18,2),
 HQLA_TOTAL NUMBER(18,2),
 L1_COUNT NUMBER(10,0),
 L2A_COUNT NUMBER(10,0),
 L2B_COUNT NUMBER(10,0),
 OUTFLOW_RETAIL NUMBER(18,2),
 OUTFLOW_CORP NUMBER(18,2),
 OUTFLOW_FI NUMBER(18,2),
 OUTFLOW_TOTAL NUMBER(18,2),
 RETAIL_ACCOUNTS NUMBER(10,0),
 CORP_ACCOUNTS NUMBER(10,0),
 FI_ACCOUNTS NUMBER(10,0)
)
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 h.AS_OF_DATE,
 h.HOLDING_ID,
 h.ASSET_TYPE,
 e.ASSET_NAME,
 e.REGULATORY_LEVEL,
 h.ISIN,
 h.SECURITY_NAME,
 h.CURRENCY,
 h.QUANTITY,
 h.MARKET_VALUE_CCY,
 h.MARKET_VALUE_CHF,
 e.HAIRCUT_PCT,
 e.HAIRCUT_FACTOR,
 h.MARKET_VALUE_CHF * e.HAIRCUT_FACTOR AS WEIGHTED_VALUE_CHF,
 h.MATURITY_DATE,
 h.CREDIT_RATING,
 h.SMI_CONSTITUENT,
 h.HQLA_ELIGIBLE,
 h.INELIGIBILITY_REASON,
 h.PORTFOLIO_CODE,
 h.CUSTODIAN,
 e.SNB_COORDINATE
FROM {{ rep_raw }}.LIQI_RAW_TB_HQLA_HOLDINGS h
INNER JOIN {{ rep_raw }}.LIQI_RAW_TB_HQLA_ELIGIBILITY e
 ON h.ASSET_TYPE = e.ASSET_TYPE
WHERE e.IS_ACTIVE = TRUE
ORDER BY h.AS_OF_DATE DESC, h.MARKET_VALUE_CHF DESC;

DEFINE VIEW {{ db }}.{{ rep_agg }}.REPP_AGG_VW_LCR_DEPOSIT_BALANCES_DETAIL
 COMMENT = 'Account-level detail view of deposit balances with run-off rate calculations and relationship-based discount logic. Provides drill-down capability from aggregate outflow metrics to individual accounts for funding stability analysis, customer relationship quality assessment, and deposit retention strategy optimization. Includes base run-off rates, relationship discounts (product count, direct debit), tenure penalties, and final calculated outflow amounts. Used by Treasury for funding planning and by Retail Banking for customer relationship management.'
 AS
SELECT
 d.AS_OF_DATE,
 d.ACCOUNT_ID,
 d.CUSTOMER_ID,
 d.DEPOSIT_TYPE,
 dt.DEPOSIT_NAME,
 d.COUNTERPARTY_TYPE,
 d.CUSTOMER_SEGMENT,
 d.CURRENCY,
 d.BALANCE_CCY,
 d.BALANCE_CHF,
 dt.BASE_RUN_OFF_RATE,
 CASE
 WHEN dt.ALLOWS_RELATIONSHIP_DISCOUNT AND d.PRODUCT_COUNT >= 3
 THEN dt.BASE_RUN_OFF_RATE - 0.02
 ELSE dt.BASE_RUN_OFF_RATE
 END AS DISCOUNT_STEP1,
 CASE
 WHEN dt.ALLOWS_RELATIONSHIP_DISCOUNT AND d.HAS_DIRECT_DEBIT
 THEN DISCOUNT_STEP1 - 0.01
 ELSE DISCOUNT_STEP1
 END AS DISCOUNT_STEP2,
 CASE
 WHEN d.ACCOUNT_TENURE_DAYS < (18 * 30)
 THEN DISCOUNT_STEP2 + 0.05
 ELSE DISCOUNT_STEP2
 END AS PENALTY_APPLIED,
 GREATEST(0.03, LEAST(1.00, PENALTY_APPLIED)) AS FINAL_RUN_OFF_RATE,
 d.BALANCE_CHF * FINAL_RUN_OFF_RATE AS OUTFLOW_AMOUNT_CHF,
 d.IS_INSURED,
 d.PRODUCT_COUNT,
 d.ACCOUNT_TENURE_DAYS,
 d.HAS_DIRECT_DEBIT,
 d.IS_OPERATIONAL,
 d.ACCOUNT_STATUS,
 dt.SNB_COORDINATE
FROM {{ rep_raw }}.LIQI_RAW_TB_DEPOSIT_BALANCES d
INNER JOIN {{ rep_raw }}.LIQI_RAW_TB_DEPOSIT_TYPES dt
 ON d.DEPOSIT_TYPE = dt.DEPOSIT_TYPE
WHERE dt.IS_ACTIVE = TRUE
ORDER BY d.AS_OF_DATE DESC, d.BALANCE_CHF DESC;
