DEFINE TABLE {{ db }}.{{ loa_agg }}.LOAA_AGG_TB_APPLICATIONS (
 APPLICATION_ID VARCHAR(50) PRIMARY KEY,
 CUSTOMER_ID VARCHAR(30),
 APPLICATION_DATE_TIME TIMESTAMP_NTZ NOT NULL,
 CHANNEL VARCHAR(50),
 COUNTRY VARCHAR(50),
 PRODUCT_ID VARCHAR(50),
 REQUESTED_AMOUNT NUMBER(18,2),
 REQUESTED_TERM_MONTHS INT,
 REQUESTED_CURRENCY VARCHAR(3),
 PURPOSE VARCHAR(100),
 ADVICE_VS_EXECUTION_ONLY VARCHAR(50),
 BROKER_ID VARCHAR(50),
 STATUS VARCHAR(50),
 CREATED_TIMESTAMP_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
 UPDATED_TIMESTAMP_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Loan applications master table. Populated from DocAI-extracted email data. Contains all mortgage and unsecured loan applications with status tracking and regulatory compliance attributes.';

DEFINE TABLE {{ db }}.{{ loa_agg }}.LOAA_AGG_TB_COLLATERAL (
 COLLATERAL_ID VARCHAR(50) PRIMARY KEY,
 PROPERTY_IDENTIFIER VARCHAR(100),
 PROPERTY_ADDRESS VARCHAR(500),
 PROPERTY_TYPE VARCHAR(50),
 OCCUPANCY_TYPE VARCHAR(50),
 CONSTRUCTION_YEAR INT,
 ENERGY_PERFORMANCE_RATING VARCHAR(10),
 VALUATION_VALUE NUMBER(18,2) NOT NULL,
 VALUATION_DATE DATE NOT NULL,
 VALUATION_METHOD VARCHAR(50),
 VALUATION_PROVIDER VARCHAR(200),
 CREATED_TIMESTAMP_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Property collateral master table. Contains valuation, property characteristics, and ESG attributes (energy ratings) for mortgage lending.';

DEFINE TABLE {{ db }}.{{ loa_agg }}.LOAA_AGG_TB_LOAN_COLLATERAL_LINK (
 LINK_ID VARCHAR(50) PRIMARY KEY,
 ACCOUNT_ID VARCHAR(50) NOT NULL,
 COLLATERAL_ID VARCHAR(50) NOT NULL,
 EFFECTIVE_FROM_DATE DATE NOT NULL,
 EFFECTIVE_TO_DATE DATE,
 CHARGE_RANK VARCHAR(10),
 CHARGE_AMOUNT NUMBER(18,2),
 COLLATERAL_ALLOCATION_PCT NUMBER(5,2),
 REGISTRATION_STATUS VARCHAR(50),
 CREATED_TIMESTAMP_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Loan-to-collateral M:M mapping table. Supports cross-collateralization and second charges. Showcase uses simple 1:1 relationships (all 1ST charge, 100% allocation).';

DEFINE TABLE {{ db }}.{{ loa_agg }}.LOAA_AGG_TB_AFFORDABILITY_ASSESSMENTS (
 AFFORDABILITY_ID VARCHAR(50) PRIMARY KEY,
 APPLICATION_ID VARCHAR(50) NOT NULL,
 CUSTOMER_ID VARCHAR(30),
 GROSS_INCOME_MONTHLY NUMBER(18,2),
 NET_INCOME_MONTHLY NUMBER(18,2),
 FIXED_INCOME_MONTHLY NUMBER(18,2),
 VARIABLE_INCOME_MONTHLY NUMBER(18,2),
 RENTAL_INCOME_MONTHLY NUMBER(18,2),
 LIVING_EXPENSES_MONTHLY NUMBER(18,2),
 TOTAL_DEBT_OBLIGATIONS_MONTHLY NUMBER(18,2),
 DTI_RATIO NUMBER(5,3),
 DSTI_RATIO NUMBER(5,3),
 AFFORDABILITY_RESULT VARCHAR(20) NOT NULL,
 AFFORDABILITY_REASON_CODES VARCHAR(500),
 INTEREST_RATE_STRESS_APPLIED_PCT NUMBER(5,4),
 STRESSED_PAYMENT_MONTHLY NUMBER(18,2),
 MODEL_EXPLAINABILITY_TOP_FACTORS VARCHAR(1000),
 CALCULATION_TIMESTAMP_UTC TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Affordability assessment snapshots for loan applications. Contains DTI/DSTI calculations with country-specific thresholds (CHE: 33%, UK: 45%, DE: 40%) and stress testing per regulatory requirements.';
