DEFINE DYNAMIC TABLE {{ db }}.{{ rep_agg }}.REPP_AGG_DT_CUSTOMER_SUMMARY(
 CUSTOMER_ID VARCHAR(30),
 FULL_NAME VARCHAR(201),
 HAS_ANOMALY BOOLEAN,
 ONBOARDING_DATE DATE,
 TOTAL_ACCOUNTS NUMBER(10,0),
 CURRENCY_COUNT NUMBER(10,0),
 ACCOUNT_CURRENCIES VARCHAR(100),
 TOTAL_TRANSACTIONS NUMBER(10,0),
 TOTAL_BASE_AMOUNT DECIMAL(28,2),
 AVG_TRANSACTION_AMOUNT DECIMAL(28,2),
 MAX_TRANSACTION_AMOUNT DECIMAL(28,2),
 ANOMALOUS_TRANSACTIONS NUMBER(10,0)
) COMMENT = 'Customer 360° Profile and Relationship Risk Assessment (CDD): To provide a consolidated, holistic view of a customer by linking personal details with aggregated transactional behavior (volume, value, account diversity).
Compliance/CDD/KYC: Used for ongoing Customer Due Diligence, monitoring relationship health, and flagging customers with anomalous behavior (HAS_ANOMALY). Risk: Identifies risk exposure through multi-currency holdings and maximum transaction size.'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 c.CUSTOMER_ID,
 CONCAT(c.FIRST_NAME, ' ', c.FAMILY_NAME) AS FULL_NAME,
 c.HAS_ANOMALY,
 c.ONBOARDING_DATE,
 COUNT(a.ACCOUNT_ID) AS TOTAL_ACCOUNTS,
 COUNT(DISTINCT a.BASE_CURRENCY) AS CURRENCY_COUNT,
 LISTAGG(DISTINCT a.BASE_CURRENCY, ', ') AS ACCOUNT_CURRENCIES,
 COUNT(t.TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
 SUM(t.AMOUNT) AS TOTAL_BASE_AMOUNT,
 AVG(t.AMOUNT) AS AVG_TRANSACTION_AMOUNT,
 MAX(t.AMOUNT) AS MAX_TRANSACTION_AMOUNT,
 COUNT(CASE WHEN t.DESCRIPTION LIKE '%[%]%' THEN 1 END) AS ANOMALOUS_TRANSACTIONS
FROM {{ crm_agg }}.CRMA_AGG_DT_CUSTOMER_360 c
LEFT JOIN {{ crm_agg }}.ACCA_AGG_DT_ACCOUNTS a ON c.CUSTOMER_ID = a.CUSTOMER_ID
LEFT JOIN {{ pay_agg }}.PAYA_AGG_DT_TRANSACTION_ANOMALIES t ON c.CUSTOMER_ID = t.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.FIRST_NAME, c.FAMILY_NAME, c.HAS_ANOMALY, c.ONBOARDING_DATE;

DEFINE DYNAMIC TABLE {{ db }}.{{ rep_agg }}.REPP_AGG_DT_DAILY_TRANSACTION_SUMMARY(
 TRANSACTION_DATE DATE,
 TRANSACTION_COUNT NUMBER(10,0),
 UNIQUE_CUSTOMERS NUMBER(10,0),
 TOTAL_BASE_AMOUNT DECIMAL(28,2),
 AVG_BASE_AMOUNT DECIMAL(28,2),
 INCOMING_COUNT NUMBER(10,0),
 OUTGOING_COUNT NUMBER(10,0),
 ANOMALOUS_COUNT NUMBER(10,0),
 CURRENCY_COUNT NUMBER(10,0)
) COMMENT = 'Operational Performance and Daily Liquidity Metrics: To monitor the banks daily activity, transaction volume, and flow (incoming vs. outgoing). This tracks the general health of the payment system and customer engagement.
Operations/Liquidity: Monitors daily transaction counts for system capacity planning. Compliance: Tracks daily count of anomalous transactions for Suspicious Activity Monitoring.'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 DATE(BOOKING_DATE) AS TRANSACTION_DATE,
 COUNT(*) AS TRANSACTION_COUNT,
 COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
 SUM(AMOUNT) AS TOTAL_BASE_AMOUNT,
 AVG(AMOUNT) AS AVG_BASE_AMOUNT,
 COUNT(CASE WHEN AMOUNT > 0 THEN 1 END) AS INCOMING_COUNT,
 COUNT(CASE WHEN AMOUNT < 0 THEN 1 END) AS OUTGOING_COUNT,
 COUNT(CASE WHEN DESCRIPTION LIKE '%[%]%' THEN 1 END) AS ANOMALOUS_COUNT,
 COUNT(DISTINCT CURRENCY) AS CURRENCY_COUNT
FROM {{ pay_agg }}.PAYA_AGG_DT_TRANSACTION_ANOMALIES
GROUP BY DATE(BOOKING_DATE)
ORDER BY TRANSACTION_DATE;

DEFINE DYNAMIC TABLE {{ db }}.{{ rep_agg }}.REPP_AGG_DT_CURRENCY_EXPOSURE_CURRENT(
 CURRENCY VARCHAR(3),
 TRANSACTION_COUNT NUMBER(10,0),
 TOTAL_ORIGINAL_AMOUNT DECIMAL(28,2),
 TOTAL_CHF_AMOUNT DECIMAL(28,2),
 AVG_FX_RATE DECIMAL(15,6),
 MIN_FX_RATE DECIMAL(15,6),
 MAX_FX_RATE DECIMAL(15,6),
 UNIQUE_CUSTOMERS NUMBER(10,0)
) COMMENT = 'Foreign Exchange (FX) Risk Monitoring (Spot): To provide a current, aggregated view of the banks non-base currency transaction exposure. Used to manage the net open position risk across all currencies.
Market Risk: Measures FX exposure for compliance with internal limits and external regulatory requirements (e.g., assessing large single currency positions).'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 CURRENCY,
 COUNT(*) AS TRANSACTION_COUNT,
 SUM(AMOUNT) AS TOTAL_ORIGINAL_AMOUNT,
 SUM(AMOUNT) AS TOTAL_CHF_AMOUNT,
 1.0 AS AVG_FX_RATE,
 1.0 AS MIN_FX_RATE,
 1.0 AS MAX_FX_RATE,
 COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS
FROM {{ pay_agg }}.PAYA_AGG_DT_TRANSACTION_ANOMALIES
WHERE CURRENCY != 'CHF'
GROUP BY CURRENCY
ORDER BY TOTAL_CHF_AMOUNT DESC;

DEFINE DYNAMIC TABLE {{ db }}.{{ rep_agg }}.REPP_AGG_DT_CURRENCY_EXPOSURE_HISTORY(
 EXPOSURE_DATE DATE,
 CURRENCY VARCHAR(3),
 DAILY_TRANSACTION_COUNT NUMBER(10,0),
 DAILY_TOTAL_AMOUNT DECIMAL(28,2),
 DAILY_AVG_AMOUNT DECIMAL(28,2),
 DAILY_MIN_AMOUNT DECIMAL(28,2),
 DAILY_MAX_AMOUNT DECIMAL(28,2),
 DAILY_UNIQUE_CUSTOMERS NUMBER(10,0),
 ROLLING_7D_TRANSACTION_COUNT NUMBER(10,0),
 ROLLING_7D_TOTAL_AMOUNT DECIMAL(28,2),
 ROLLING_7D_AVG_DAILY_AMOUNT DECIMAL(28,2),
 AMOUNT_30_DAYS_AGO DECIMAL(28,2),
 GROWTH_RATE_30D_PERCENT DECIMAL(8,2),
 DAILY_VOLUME_CATEGORY VARCHAR(20),
 DAILY_EXPOSURE_CATEGORY VARCHAR(20)
) COMMENT = 'FX Market Trend and Volatility Analysis: To provide a time series of currency exposure, including 7-day rolling totals and 30-day growth rates. This enables sophisticated analysis of market risk trends.
Market Risk/Treasury: Used for analyzing currency volatility, forecasting future liquidity needs, and classifying exposure into high, medium, and low categories for risk appetite adherence.'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 DATE(BOOKING_DATE) AS EXPOSURE_DATE,
 CURRENCY,
 COUNT(*) AS DAILY_TRANSACTION_COUNT,
 SUM(AMOUNT) AS DAILY_TOTAL_AMOUNT,
 AVG(AMOUNT) AS DAILY_AVG_AMOUNT,
 MIN(AMOUNT) AS DAILY_MIN_AMOUNT,
 MAX(AMOUNT) AS DAILY_MAX_AMOUNT,
 COUNT(DISTINCT CUSTOMER_ID) AS DAILY_UNIQUE_CUSTOMERS,

 SUM(COUNT(*)) OVER (
 PARTITION BY CURRENCY
 ORDER BY DATE(BOOKING_DATE)
 ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
 ) AS ROLLING_7D_TRANSACTION_COUNT,

 SUM(SUM(AMOUNT)) OVER (
 PARTITION BY CURRENCY
 ORDER BY DATE(BOOKING_DATE)
 ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
 ) AS ROLLING_7D_TOTAL_AMOUNT,

 AVG(SUM(AMOUNT)) OVER (
 PARTITION BY CURRENCY
 ORDER BY DATE(BOOKING_DATE)
 ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
 ) AS ROLLING_7D_AVG_DAILY_AMOUNT,

 LAG(SUM(AMOUNT), 30) OVER (
 PARTITION BY CURRENCY
 ORDER BY DATE(BOOKING_DATE)
 ) AS AMOUNT_30_DAYS_AGO,

 CASE
 WHEN LAG(SUM(AMOUNT), 30) OVER (PARTITION BY CURRENCY ORDER BY DATE(BOOKING_DATE)) > 0
 THEN ROUND(
 ((SUM(AMOUNT) - LAG(SUM(AMOUNT), 30) OVER (PARTITION BY CURRENCY ORDER BY DATE(BOOKING_DATE))) /
 LAG(SUM(AMOUNT), 30) OVER (PARTITION BY CURRENCY ORDER BY DATE(BOOKING_DATE))) * 100, 2
 )
 ELSE NULL
 END AS GROWTH_RATE_30D_PERCENT,

 CASE
 WHEN COUNT(*) > 100 THEN 'HIGH_VOLUME'
 WHEN COUNT(*) > 50 THEN 'MEDIUM_VOLUME'
 ELSE 'LOW_VOLUME'
 END AS DAILY_VOLUME_CATEGORY,

 CASE
 WHEN SUM(AMOUNT) > 1000000 THEN 'HIGH_EXPOSURE'
 WHEN SUM(AMOUNT) > 100000 THEN 'MEDIUM_EXPOSURE'
 ELSE 'LOW_EXPOSURE'
 END AS DAILY_EXPOSURE_CATEGORY

FROM {{ pay_agg }}.PAYA_AGG_DT_TRANSACTION_ANOMALIES
WHERE CURRENCY != 'CHF'
GROUP BY DATE(BOOKING_DATE), CURRENCY
ORDER BY EXPOSURE_DATE DESC, DAILY_TOTAL_AMOUNT DESC;

DEFINE DYNAMIC TABLE {{ db }}.{{ rep_agg }}.REPP_AGG_DT_CURRENCY_SETTLEMENT_EXPOSURE(
 SETTLEMENT_DATE DATE,
 CURRENCY VARCHAR(3),
 SETTLEMENT_TRANSACTION_COUNT NUMBER(10,0),
 SETTLEMENT_TOTAL_AMOUNT DECIMAL(28,2),
 AVG_SETTLEMENT_DAYS DECIMAL(8,2),
 SAME_DAY_SETTLEMENTS NUMBER(10,0),
 T_PLUS_1_SETTLEMENTS NUMBER(10,0),
 T_PLUS_2_3_SETTLEMENTS NUMBER(10,0),
 DELAYED_SETTLEMENTS NUMBER(10,0),
 BACKDATED_SETTLEMENTS NUMBER(10,0),
 SETTLEMENT_RISK_LEVEL VARCHAR(30),
 SETTLEMENT_TIMING_TYPE VARCHAR(30)
) COMMENT = 'Settlement Timing and Liquidity Risk Analysis: To analyze the timing of fund settlements (VALUE_DATE vs. BOOKING_DATE) for non-base currencies. It focuses on the settlement lag to manage liquidity and operational risk.
Operational Risk/Treasury: Flags transactions with high settlement risk (delayed or backdated) which are critical for operational stability, liquidity planning, and identifying potential non-compliance patterns.'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 DATE(VALUE_DATE) AS SETTLEMENT_DATE,
 CURRENCY,
 COUNT(*) AS SETTLEMENT_TRANSACTION_COUNT,
 SUM(AMOUNT) AS SETTLEMENT_TOTAL_AMOUNT,
 AVG(DATEDIFF(DAY, BOOKING_DATE, VALUE_DATE)) AS AVG_SETTLEMENT_DAYS,

 COUNT(CASE WHEN DATEDIFF(DAY, BOOKING_DATE, VALUE_DATE) = 0 THEN 1 END) AS SAME_DAY_SETTLEMENTS,
 COUNT(CASE WHEN DATEDIFF(DAY, BOOKING_DATE, VALUE_DATE) = 1 THEN 1 END) AS T_PLUS_1_SETTLEMENTS,
 COUNT(CASE WHEN DATEDIFF(DAY, BOOKING_DATE, VALUE_DATE) BETWEEN 2 AND 3 THEN 1 END) AS T_PLUS_2_3_SETTLEMENTS,
 COUNT(CASE WHEN DATEDIFF(DAY, BOOKING_DATE, VALUE_DATE) > 5 THEN 1 END) AS DELAYED_SETTLEMENTS,
 COUNT(CASE WHEN VALUE_DATE < DATE(BOOKING_DATE) THEN 1 END) AS BACKDATED_SETTLEMENTS,

 CASE
 WHEN COUNT(CASE WHEN DATEDIFF(DAY, BOOKING_DATE, VALUE_DATE) > 5 THEN 1 END) > 0
 THEN 'HIGH_SETTLEMENT_RISK'
 WHEN COUNT(CASE WHEN DATEDIFF(DAY, BOOKING_DATE, VALUE_DATE) > 3 THEN 1 END) >
 COUNT(*) * 0.1
 THEN 'MEDIUM_SETTLEMENT_RISK'
 ELSE 'LOW_SETTLEMENT_RISK'
 END AS SETTLEMENT_RISK_LEVEL,

 CASE
 WHEN DAYOFWEEK(DATE(VALUE_DATE)) IN (1,7) THEN 'WEEKEND_SETTLEMENT'
 ELSE 'WEEKDAY_SETTLEMENT'
 END AS SETTLEMENT_TIMING_TYPE

FROM {{ pay_agg }}.PAYA_AGG_DT_TRANSACTION_ANOMALIES
WHERE CURRENCY != 'CHF'
GROUP BY DATE(VALUE_DATE), CURRENCY
ORDER BY SETTLEMENT_DATE DESC, SETTLEMENT_TOTAL_AMOUNT DESC;

DEFINE DYNAMIC TABLE {{ db }}.{{ rep_agg }}.REPP_AGG_DT_ANOMALY_ANALYSIS(
 CUSTOMER_ID VARCHAR(30),
 FULL_NAME VARCHAR(201),
 IS_ANOMALOUS_CUSTOMER BOOLEAN,
 TOTAL_TRANSACTIONS NUMBER(10,0),
 ANOMALOUS_TRANSACTIONS NUMBER(10,0),
 ANOMALY_PERCENTAGE DECIMAL(8,2),
 ANOMALOUS_AMOUNT DECIMAL(28,2),
 ANOMALY_TYPES VARCHAR(2000)
) COMMENT = 'Customer-level anomaly analysis for compliance monitoring, AML investigation, and suspicious activity reporting.
Compliance/AML: Directly supports Anti-Money Laundering operations by identifying and prioritizing high-risk customers for further AML investigation and the generation of Suspicious Activity Reports (SARs).'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 c.CUSTOMER_ID,
 CONCAT(c.FIRST_NAME, ' ', c.FAMILY_NAME) AS FULL_NAME,
 c.HAS_ANOMALY AS IS_ANOMALOUS_CUSTOMER,
 COUNT(t.TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
 COUNT(CASE WHEN t.DESCRIPTION LIKE '%[%]%' THEN 1 END) AS ANOMALOUS_TRANSACTIONS,
 ROUND(COUNT(CASE WHEN t.DESCRIPTION LIKE '%[%]%' THEN 1 END) * 100.0 / COUNT(t.TRANSACTION_ID), 2) AS ANOMALY_PERCENTAGE,
 SUM(CASE WHEN t.DESCRIPTION LIKE '%[%]%' THEN t.AMOUNT ELSE 0 END) AS ANOMALOUS_AMOUNT,
 LISTAGG(DISTINCT
 CASE WHEN t.DESCRIPTION LIKE '%[%]%'
 THEN REGEXP_REPLACE(t.DESCRIPTION, '.*\[(.*?)\].*', '\\1')
 END, ', ') AS ANOMALY_TYPES
FROM {{ crm_agg }}.CRMA_AGG_DT_CUSTOMER_360 c
LEFT JOIN {{ db }}.{{ pay_agg }}.PAYA_AGG_DT_TRANSACTION_ANOMALIES t ON c.CUSTOMER_ID = t.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.FIRST_NAME, c.FAMILY_NAME, c.HAS_ANOMALY
HAVING COUNT(t.TRANSACTION_ID) > 0
ORDER BY ANOMALY_PERCENTAGE DESC, ANOMALOUS_AMOUNT DESC;

DEFINE DYNAMIC TABLE {{ db }}.{{ rep_agg }}.REPP_AGG_DT_HIGH_RISK_PATTERNS(
 TRANSACTION_ID VARCHAR(50),
 CUSTOMER_ID VARCHAR(30),
 BOOKING_DATE TIMESTAMP_NTZ,
 VALUE_DATE DATE,
 AMOUNT DECIMAL(28,2),
 CURRENCY VARCHAR(3),
 DIRECTION VARCHAR(3),
 DESCRIPTION VARCHAR(500),
 RISK_CATEGORY VARCHAR(30),
 SETTLEMENT_DAYS NUMBER(10,0)
) TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 TRANSACTION_ID,
 CUSTOMER_ID,
 BOOKING_DATE,
 VALUE_DATE,
 AMOUNT,
 CURRENCY,
 CASE WHEN AMOUNT > 0 THEN 'IN' ELSE 'OUT' END AS DIRECTION,
 DESCRIPTION,
 CASE
 WHEN AMOUNT >= 10000 THEN 'HIGH_AMOUNT'
 WHEN DESCRIPTION LIKE '%[%]%' THEN 'ANOMALOUS'
 WHEN CURRENCY != 'CHF' AND AMOUNT >= 5000 THEN 'HIGH_FX_AMOUNT'
 WHEN COUNTERPARTY_ACCOUNT LIKE 'OFF_SHORE_%' THEN 'OFFSHORE'
 WHEN COUNTERPARTY_ACCOUNT LIKE 'CRYPTO_%' THEN 'CRYPTO'
 WHEN HOUR(BOOKING_DATE) NOT BETWEEN 9 AND 17 THEN 'OFF_HOURS'
 WHEN VALUE_DATE < DATE(BOOKING_DATE) THEN 'BACKDATED_SETTLEMENT'
 WHEN DATEDIFF(DAY, BOOKING_DATE, VALUE_DATE) > 5 THEN 'DELAYED_SETTLEMENT'
 ELSE 'OTHER'
 END AS RISK_CATEGORY,
 DATEDIFF(DAY, BOOKING_DATE, VALUE_DATE) AS SETTLEMENT_DAYS
FROM {{ pay_agg }}.PAYA_AGG_DT_TRANSACTION_ANOMALIES
WHERE
 AMOUNT >= 10000
 OR DESCRIPTION LIKE '%[%]%'
 OR (CURRENCY != 'CHF' AND AMOUNT >= 5000)
 OR COUNTERPARTY_ACCOUNT LIKE 'OFF_SHORE_%'
 OR COUNTERPARTY_ACCOUNT LIKE 'CRYPTO_%'
 OR HOUR(BOOKING_DATE) NOT BETWEEN 9 AND 17
 OR VALUE_DATE < DATE(BOOKING_DATE)
 OR DATEDIFF(DAY, BOOKING_DATE, VALUE_DATE) > 5
ORDER BY AMOUNT DESC, BOOKING_DATE DESC;

DEFINE DYNAMIC TABLE {{ db }}.{{ rep_agg }}.REPP_AGG_DT_SETTLEMENT_ANALYSIS(
 BOOKING_DATE DATE,
 VALUE_DATE DATE,
 SETTLEMENT_DAYS NUMBER(10,0),
 TRANSACTION_COUNT NUMBER(10,0),
 UNIQUE_CUSTOMERS NUMBER(10,0),
 TOTAL_AMOUNT DECIMAL(28,2),
 AVG_AMOUNT DECIMAL(28,2),
 BACKDATED_COUNT NUMBER(10,0),
 DELAYED_COUNT NUMBER(10,0),
 SAME_DAY_COUNT NUMBER(10,0),
 NEXT_DAY_COUNT NUMBER(10,0),
 T_PLUS_2_3_COUNT NUMBER(10,0)
) COMMENT = 'Aggregated Operational Settlement Analysis: To provide a view of overall settlement efficiency by grouping transactions based on the number of settlement days.
Operations/Liquidity: Used to manage and improve payment processing efficiency, tracking the volume of same-day, next-day, and delayed settlements. Critical for monitoring compliance with real-time or T+X settlement mandates.'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 DATE(BOOKING_DATE) AS BOOKING_DATE,
 DATE(VALUE_DATE) AS VALUE_DATE,
 DATEDIFF(DAY, BOOKING_DATE, VALUE_DATE) AS SETTLEMENT_DAYS,
 COUNT(*) AS TRANSACTION_COUNT,
 COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
 SUM(AMOUNT) AS TOTAL_AMOUNT,
 AVG(AMOUNT) AS AVG_AMOUNT,
 COUNT(CASE WHEN VALUE_DATE < DATE(BOOKING_DATE) THEN 1 END) AS BACKDATED_COUNT,
 COUNT(CASE WHEN DATEDIFF(DAY, BOOKING_DATE, VALUE_DATE) > 5 THEN 1 END) AS DELAYED_COUNT,
 COUNT(CASE WHEN DATEDIFF(DAY, BOOKING_DATE, VALUE_DATE) = 0 THEN 1 END) AS SAME_DAY_COUNT,
 COUNT(CASE WHEN DATEDIFF(DAY, BOOKING_DATE, VALUE_DATE) = 1 THEN 1 END) AS NEXT_DAY_COUNT,
 COUNT(CASE WHEN DATEDIFF(DAY, BOOKING_DATE, VALUE_DATE) BETWEEN 2 AND 3 THEN 1 END) AS T_PLUS_2_3_COUNT
FROM {{ pay_agg }}.PAYA_AGG_DT_TRANSACTION_ANOMALIES
GROUP BY DATE(BOOKING_DATE), DATE(VALUE_DATE), DATEDIFF(DAY, BOOKING_DATE, VALUE_DATE)
ORDER BY BOOKING_DATE DESC, SETTLEMENT_DAYS DESC;

DEFINE DYNAMIC TABLE {{ db }}.{{ rep_agg }}.REPP_AGG_DT_LIFECYCLE_ANOMALIES(
 CUSTOMER_ID VARCHAR(30),
 FULL_NAME VARCHAR(201),
 LIFECYCLE_EVENT_ID VARCHAR(50),
 EVENT_TYPE VARCHAR(30),
 EVENT_DATE DATE,
 DAYS_DORMANT_BEFORE_EVENT NUMBER(10,0),
 TRANSACTION_ID VARCHAR(50),
 TRANSACTION_DATE DATE,
 TRANSACTION_AMOUNT DECIMAL(15,2),
 ANOMALY_SCORE NUMBER(8,2),
 ANOMALY_LEVEL VARCHAR(30),
 DAYS_BETWEEN_EVENT_AND_TRANSACTION NUMBER(10,0),
 AML_RISK_LEVEL VARCHAR(30),
 REQUIRES_SAR_FILING BOOLEAN,
 INVESTIGATION_STATUS VARCHAR(30),
 LAST_UPDATED TIMESTAMP_NTZ
) COMMENT = 'Lifecycle event correlation with transaction anomalies for AML detection. Identifies suspicious patterns like dormant accounts suddenly active after reactivation events, address changes followed by high-value transfers, and employment changes with unusual transaction patterns. Used for SAR filing and compliance investigations.'
TARGET_LAG = '{{ lag }}' WAREHOUSE = {{ wh }}
AS
SELECT
 c.CUSTOMER_ID,
 CONCAT(c.FIRST_NAME, ' ', c.FAMILY_NAME) AS FULL_NAME,

 e.EVENT_ID AS LIFECYCLE_EVENT_ID,
 e.EVENT_TYPE,
 e.EVENT_DATE,

 DATEDIFF(DAY, prev_txn.LAST_TXN_BEFORE_EVENT, e.EVENT_DATE) AS DAYS_DORMANT_BEFORE_EVENT,

 a.TRANSACTION_ID,
 a.BOOKING_DATE::DATE AS TRANSACTION_DATE,
 a.AMOUNT AS TRANSACTION_AMOUNT,
 a.COMPOSITE_ANOMALY_SCORE AS ANOMALY_SCORE,
 a.OVERALL_ANOMALY_CLASSIFICATION AS ANOMALY_LEVEL,

 DATEDIFF(DAY, e.EVENT_DATE, a.BOOKING_DATE::DATE) AS DAYS_BETWEEN_EVENT_AND_TRANSACTION,

 CASE
 WHEN a.OVERALL_ANOMALY_CLASSIFICATION = 'CRITICAL' AND e.EVENT_TYPE IN ('REACTIVATION', 'ADDRESS_CHANGE') THEN 'CRITICAL'
 WHEN a.OVERALL_ANOMALY_CLASSIFICATION IN ('CRITICAL', 'HIGH') AND DATEDIFF(DAY, prev_txn.LAST_TXN_BEFORE_EVENT, e.EVENT_DATE) > 180 THEN 'HIGH'
 WHEN a.OVERALL_ANOMALY_CLASSIFICATION = 'HIGH' THEN 'MEDIUM'
 ELSE 'LOW'
 END AS AML_RISK_LEVEL,

 CASE
 WHEN a.OVERALL_ANOMALY_CLASSIFICATION = 'CRITICAL'
 AND e.EVENT_TYPE IN ('REACTIVATION', 'ADDRESS_CHANGE')
 AND DATEDIFF(DAY, prev_txn.LAST_TXN_BEFORE_EVENT, e.EVENT_DATE) > 180
 THEN TRUE
 ELSE FALSE
 END AS REQUIRES_SAR_FILING,

 'OPEN' AS INVESTIGATION_STATUS,

 CURRENT_TIMESTAMP() AS LAST_UPDATED

FROM {{ crm_raw }}.CRMI_RAW_TB_CUSTOMER c

INNER JOIN {{ crm_raw }}.CRMI_RAW_TB_CUSTOMER_EVENT e
 ON c.CUSTOMER_ID = e.CUSTOMER_ID
 AND e.EVENT_TYPE IN ('REACTIVATION', 'ADDRESS_CHANGE', 'EMPLOYMENT_CHANGE')

INNER JOIN {{ pay_agg }}.PAYA_AGG_DT_TRANSACTION_ANOMALIES a
 ON c.CUSTOMER_ID = a.CUSTOMER_ID
 AND a.BOOKING_DATE::DATE BETWEEN e.EVENT_DATE AND DATEADD(DAY, 30, e.EVENT_DATE)
 AND a.OVERALL_ANOMALY_CLASSIFICATION IN ('CRITICAL', 'HIGH')

LEFT JOIN LATERAL (
 SELECT MAX(t.BOOKING_DATE::DATE) AS LAST_TXN_BEFORE_EVENT
 FROM {{ crm_raw }}.ACCI_RAW_TB_ACCOUNTS acc
 INNER JOIN {{ pay_raw }}.PAYI_RAW_TB_TRANSACTIONS t ON acc.ACCOUNT_ID = t.ACCOUNT_ID
 WHERE acc.CUSTOMER_ID = c.CUSTOMER_ID
 AND t.BOOKING_DATE::DATE < e.EVENT_DATE
) prev_txn

WHERE DATEDIFF(DAY, prev_txn.LAST_TXN_BEFORE_EVENT, e.EVENT_DATE) > 30

ORDER BY AML_RISK_LEVEL DESC, ANOMALY_SCORE DESC;
