/*
 * 565_LOAR_reporting.sql
 * Loan reporting: portfolio, delinquency, compliance views
 */
DEFINE DYNAMIC TABLE {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_PORTFOLIO_SUMMARY (
    AS_OF_DATE DATE COMMENT 'Reporting date for snapshot',
    PRODUCT_TYPE VARCHAR(50) COMMENT 'Product type: MORTGAGE, PERSONAL_LOAN',
    COUNTRY VARCHAR(50) COMMENT 'Country code (CHE, GBR, DEU)',
    APPLICATION_STATUS VARCHAR(50) COMMENT 'Application status: APPROVED, DECLINED, UNDER_REVIEW',
    LOAN_COUNT INT COMMENT 'Number of applications in this category',
    TOTAL_REQUESTED_AMOUNT NUMBER(18,2) COMMENT 'Total requested loan amount',
    AVG_REQUESTED_AMOUNT NUMBER(18,2) COMMENT 'Average requested loan amount',
    MIN_REQUESTED_AMOUNT NUMBER(18,2) COMMENT 'Minimum requested loan amount',
    MAX_REQUESTED_AMOUNT NUMBER(18,2) COMMENT 'Maximum requested loan amount',
    AVG_TERM_MONTHS INT COMMENT 'Average loan term in months',
    CALCULATION_TIMESTAMP TIMESTAMP_NTZ COMMENT 'When this aggregation was calculated'
)
COMMENT = 'Portfolio summary aggregated by product type, country, and application status. Updates every 60 minutes for near real-time portfolio monitoring.'
TARGET_LAG = '{{ lag }}'
WAREHOUSE = {{ wh }}
AS
SELECT
    CURRENT_DATE() as AS_OF_DATE,
    COALESCE(p.PRODUCT_TYPE, 'Unknown') as PRODUCT_TYPE,
    a.COUNTRY,
    a.STATUS as APPLICATION_STATUS,
    COUNT(*) as LOAN_COUNT,
    SUM(a.REQUESTED_AMOUNT) as TOTAL_REQUESTED_AMOUNT,
    ROUND(AVG(a.REQUESTED_AMOUNT), 2) as AVG_REQUESTED_AMOUNT,
    MIN(a.REQUESTED_AMOUNT) as MIN_REQUESTED_AMOUNT,
    MAX(a.REQUESTED_AMOUNT) as MAX_REQUESTED_AMOUNT,
    ROUND(AVG(a.REQUESTED_TERM_MONTHS), 0) as AVG_TERM_MONTHS,
    CURRENT_TIMESTAMP() as CALCULATION_TIMESTAMP
FROM {{ db }}.{{ loa_agg }}.LOAA_AGG_TB_APPLICATIONS a
LEFT JOIN {{ db }}.{{ loa_raw }}.LOAI_REF_TB_PRODUCT_CATALOGUE p ON a.PRODUCT_ID = p.PRODUCT_ID
GROUP BY AS_OF_DATE, PRODUCT_TYPE, a.COUNTRY, a.STATUS;

DEFINE DYNAMIC TABLE {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_LTV_DISTRIBUTION (
    AS_OF_DATE DATE COMMENT 'Reporting date for snapshot',
    LTV_BUCKET VARCHAR(20) COMMENT 'LTV bucket: 0-50%, 50-60%, 60-70%, 70-80%, 80-90%, >90%',
    LTV_BUCKET_SORT_ORDER INT COMMENT 'Sort order for LTV buckets (1-6)',
    LOAN_COUNT INT COMMENT 'Number of loans in this LTV bucket',
    TOTAL_LOAN_AMOUNT NUMBER(18,2) COMMENT 'Total loan amount in this bucket',
    AVG_LTV_PCT NUMBER(5,2) COMMENT 'Average LTV percentage in this bucket',
    TOTAL_COLLATERAL_VALUE NUMBER(18,2) COMMENT 'Total collateral value in this bucket',
    PCT_OF_TOTAL_LOANS NUMBER(5,2) COMMENT 'Percentage of total loan count',
    CALCULATION_TIMESTAMP TIMESTAMP_NTZ COMMENT 'When this aggregation was calculated'
)
COMMENT = 'LTV distribution by buckets for risk concentration analysis. Shows loan volumes and values across LTV ranges per regulatory requirements.'
TARGET_LAG = '{{ lag }}'
WAREHOUSE = {{ wh }}
AS
WITH ltv_calc AS (
    SELECT
        a.APPLICATION_ID,
        a.REQUESTED_AMOUNT,
        col.VALUATION_VALUE,
        ROUND((a.REQUESTED_AMOUNT / NULLIF(col.VALUATION_VALUE, 0)) * 100, 2) as LTV_PCT,
        CASE 
            WHEN (a.REQUESTED_AMOUNT / NULLIF(col.VALUATION_VALUE, 0)) * 100 <= 50 THEN '0-50%'
            WHEN (a.REQUESTED_AMOUNT / NULLIF(col.VALUATION_VALUE, 0)) * 100 <= 60 THEN '50-60%'
            WHEN (a.REQUESTED_AMOUNT / NULLIF(col.VALUATION_VALUE, 0)) * 100 <= 70 THEN '60-70%'
            WHEN (a.REQUESTED_AMOUNT / NULLIF(col.VALUATION_VALUE, 0)) * 100 <= 80 THEN '70-80%'
            WHEN (a.REQUESTED_AMOUNT / NULLIF(col.VALUATION_VALUE, 0)) * 100 <= 90 THEN '80-90%'
            ELSE '>90%'
        END as LTV_BUCKET,
        CASE 
            WHEN (a.REQUESTED_AMOUNT / NULLIF(col.VALUATION_VALUE, 0)) * 100 <= 50 THEN 1
            WHEN (a.REQUESTED_AMOUNT / NULLIF(col.VALUATION_VALUE, 0)) * 100 <= 60 THEN 2
            WHEN (a.REQUESTED_AMOUNT / NULLIF(col.VALUATION_VALUE, 0)) * 100 <= 70 THEN 3
            WHEN (a.REQUESTED_AMOUNT / NULLIF(col.VALUATION_VALUE, 0)) * 100 <= 80 THEN 4
            WHEN (a.REQUESTED_AMOUNT / NULLIF(col.VALUATION_VALUE, 0)) * 100 <= 90 THEN 5
            ELSE 6
        END as LTV_BUCKET_SORT_ORDER
    FROM {{ db }}.{{ loa_agg }}.LOAA_AGG_TB_APPLICATIONS a
    JOIN {{ db }}.{{ loa_agg }}.LOAA_AGG_TB_LOAN_COLLATERAL_LINK lnk 
        ON a.APPLICATION_ID = lnk.ACCOUNT_ID
    JOIN {{ db }}.{{ loa_agg }}.LOAA_AGG_TB_COLLATERAL col 
        ON lnk.COLLATERAL_ID = col.COLLATERAL_ID
    WHERE col.VALUATION_VALUE > 0
)
SELECT
    CURRENT_DATE() as AS_OF_DATE,
    LTV_BUCKET,
    LTV_BUCKET_SORT_ORDER,
    COUNT(*) as LOAN_COUNT,
    SUM(REQUESTED_AMOUNT) as TOTAL_LOAN_AMOUNT,
    ROUND(AVG(LTV_PCT), 2) as AVG_LTV_PCT,
    SUM(VALUATION_VALUE) as TOTAL_COLLATERAL_VALUE,
    ROUND((COUNT(*) * 100.0 / SUM(COUNT(*)) OVER ()), 2) as PCT_OF_TOTAL_LOANS,
    CURRENT_TIMESTAMP() as CALCULATION_TIMESTAMP
FROM ltv_calc
GROUP BY AS_OF_DATE, LTV_BUCKET, LTV_BUCKET_SORT_ORDER;

DEFINE DYNAMIC TABLE {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_APPLICATION_FUNNEL (
    AS_OF_DATE DATE COMMENT 'Reporting date for snapshot',
    PRODUCT_TYPE VARCHAR(50) COMMENT 'Product type: MORTGAGE, PERSONAL_LOAN',
    COUNTRY VARCHAR(50) COMMENT 'Country code',
    CHANNEL VARCHAR(50) COMMENT 'Application channel: EMAIL, PORTAL, BRANCH',
    TOTAL_APPLICATIONS INT COMMENT 'Total number of applications',
    APPROVED_COUNT INT COMMENT 'Number of approved applications',
    DECLINED_COUNT INT COMMENT 'Number of declined applications',
    UNDER_REVIEW_COUNT INT COMMENT 'Number of applications under review',
    APPROVAL_RATE_PCT NUMBER(5,2) COMMENT 'Approval rate percentage',
    DECLINE_RATE_PCT NUMBER(5,2) COMMENT 'Decline rate percentage',
    AVG_REQUESTED_AMOUNT NUMBER(18,2) COMMENT 'Average requested amount',
    CALCULATION_TIMESTAMP TIMESTAMP_NTZ COMMENT 'When this aggregation was calculated'
)
COMMENT = 'Application funnel metrics by product, country, and channel. Shows approval rates and conversion metrics for loan origination monitoring.'
TARGET_LAG = '{{ lag }}'
WAREHOUSE = {{ wh }}
AS
SELECT
    CURRENT_DATE() as AS_OF_DATE,
    COALESCE(p.PRODUCT_TYPE, 'Unknown') as PRODUCT_TYPE,
    a.COUNTRY,
    a.CHANNEL,
    COUNT(*) as TOTAL_APPLICATIONS,
    SUM(CASE WHEN a.STATUS = 'APPROVED' THEN 1 ELSE 0 END) as APPROVED_COUNT,
    SUM(CASE WHEN a.STATUS = 'DECLINED' THEN 1 ELSE 0 END) as DECLINED_COUNT,
    SUM(CASE WHEN a.STATUS = 'UNDER_REVIEW' THEN 1 ELSE 0 END) as UNDER_REVIEW_COUNT,
    ROUND((SUM(CASE WHEN a.STATUS = 'APPROVED' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2) as APPROVAL_RATE_PCT,
    ROUND((SUM(CASE WHEN a.STATUS = 'DECLINED' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2) as DECLINE_RATE_PCT,
    ROUND(AVG(a.REQUESTED_AMOUNT), 2) as AVG_REQUESTED_AMOUNT,
    CURRENT_TIMESTAMP() as CALCULATION_TIMESTAMP
FROM {{ db }}.{{ loa_agg }}.LOAA_AGG_TB_APPLICATIONS a
LEFT JOIN {{ db }}.{{ loa_raw }}.LOAI_REF_TB_PRODUCT_CATALOGUE p ON a.PRODUCT_ID = p.PRODUCT_ID
GROUP BY AS_OF_DATE, PRODUCT_TYPE, a.COUNTRY, a.CHANNEL;

DEFINE DYNAMIC TABLE {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_AFFORDABILITY_SUMMARY (
    AS_OF_DATE DATE COMMENT 'Reporting date for snapshot',
    COUNTRY VARCHAR(50) COMMENT 'Country code',
    AFFORDABILITY_RESULT VARCHAR(20) COMMENT 'Affordability result: PASS, FAIL',
    ASSESSMENT_COUNT INT COMMENT 'Number of assessments',
    AVG_DTI_RATIO_PCT NUMBER(5,2) COMMENT 'Average DTI ratio percentage',
    AVG_DSTI_RATIO_PCT NUMBER(5,2) COMMENT 'Average DSTI ratio percentage',
    AVG_GROSS_INCOME NUMBER(18,2) COMMENT 'Average gross monthly income',
    AVG_DEBT_OBLIGATIONS NUMBER(18,2) COMMENT 'Average monthly debt obligations',
    PASS_RATE_PCT NUMBER(5,2) COMMENT 'Percentage of assessments that passed',
    CALCULATION_TIMESTAMP TIMESTAMP_NTZ COMMENT 'When this aggregation was calculated'
)
COMMENT = 'Affordability assessment summary by country and outcome. Shows DTI/DSTI metrics and pass rates for regulatory compliance reporting.'
TARGET_LAG = '{{ lag }}'
WAREHOUSE = {{ wh }}
AS
SELECT
    CURRENT_DATE() as AS_OF_DATE,
    a.COUNTRY,
    aff.AFFORDABILITY_RESULT,
    COUNT(*) as ASSESSMENT_COUNT,
    ROUND(AVG(aff.DTI_RATIO) * 100, 2) as AVG_DTI_RATIO_PCT,
    ROUND(AVG(aff.DSTI_RATIO) * 100, 2) as AVG_DSTI_RATIO_PCT,
    ROUND(AVG(aff.GROSS_INCOME_MONTHLY), 2) as AVG_GROSS_INCOME,
    ROUND(AVG(aff.TOTAL_DEBT_OBLIGATIONS_MONTHLY), 2) as AVG_DEBT_OBLIGATIONS,
    ROUND((SUM(CASE WHEN aff.AFFORDABILITY_RESULT = 'PASS' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0)), 2) as PASS_RATE_PCT,
    CURRENT_TIMESTAMP() as CALCULATION_TIMESTAMP
FROM {{ db }}.{{ loa_agg }}.LOAA_AGG_TB_AFFORDABILITY_ASSESSMENTS aff
JOIN {{ db }}.{{ loa_agg }}.LOAA_AGG_TB_APPLICATIONS a ON aff.APPLICATION_ID = a.APPLICATION_ID
GROUP BY AS_OF_DATE, a.COUNTRY, aff.AFFORDABILITY_RESULT;

DEFINE DYNAMIC TABLE {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_CUSTOMER_LOAN_SUMMARY (
    CUSTOMER_ID VARCHAR(30) COMMENT 'FK to {{ db }}.{{ crm_agg }}.CRMA_AGG_DT_CUSTOMER_360',
    TOTAL_APPLICATIONS INT COMMENT 'Total number of loan applications by this customer',
    APPROVED_APPLICATIONS INT COMMENT 'Number of approved applications',
    DECLINED_APPLICATIONS INT COMMENT 'Number of declined applications',
    TOTAL_APPROVED_AMOUNT NUMBER(18,2) COMMENT 'Total approved loan amount',
    AVG_REQUESTED_AMOUNT NUMBER(18,2) COMMENT 'Average requested loan amount',
    LATEST_APPLICATION_DATE TIMESTAMP_NTZ COMMENT 'Date of most recent application',
    LATEST_APPLICATION_STATUS VARCHAR(50) COMMENT 'Status of most recent application',
    AVG_LTV_PCT NUMBER(5,2) COMMENT 'Average LTV across all applications',
    AFFORDABILITY_PASS_COUNT INT COMMENT 'Number of affordability assessments passed',
    AFFORDABILITY_FAIL_COUNT INT COMMENT 'Number of affordability assessments failed',
    CALCULATION_TIMESTAMP TIMESTAMP_NTZ COMMENT 'When this aggregation was calculated'
)
COMMENT = 'Per-customer loan summary for Customer 360 integration. Aggregates all loan applications and assessments by customer.'
TARGET_LAG = '{{ lag }}'
WAREHOUSE = {{ wh }}
AS
WITH ltv_calc AS (
    SELECT
        a.CUSTOMER_ID,
        a.APPLICATION_ID,
        ROUND((a.REQUESTED_AMOUNT / NULLIF(col.VALUATION_VALUE, 0)) * 100, 2) as LTV_PCT
    FROM {{ db }}.{{ loa_agg }}.LOAA_AGG_TB_APPLICATIONS a
    LEFT JOIN {{ db }}.{{ loa_agg }}.LOAA_AGG_TB_LOAN_COLLATERAL_LINK lnk ON a.APPLICATION_ID = lnk.ACCOUNT_ID
    LEFT JOIN {{ db }}.{{ loa_agg }}.LOAA_AGG_TB_COLLATERAL col ON lnk.COLLATERAL_ID = col.COLLATERAL_ID
)
SELECT
    a.CUSTOMER_ID,
    COUNT(*) as TOTAL_APPLICATIONS,
    SUM(CASE WHEN a.STATUS = 'APPROVED' THEN 1 ELSE 0 END) as APPROVED_APPLICATIONS,
    SUM(CASE WHEN a.STATUS = 'DECLINED' THEN 1 ELSE 0 END) as DECLINED_APPLICATIONS,
    SUM(CASE WHEN a.STATUS = 'APPROVED' THEN a.REQUESTED_AMOUNT ELSE 0 END) as TOTAL_APPROVED_AMOUNT,
    ROUND(AVG(a.REQUESTED_AMOUNT), 2) as AVG_REQUESTED_AMOUNT,
    MAX(a.APPLICATION_DATE_TIME) as LATEST_APPLICATION_DATE,
    MAX_BY(a.STATUS, a.APPLICATION_DATE_TIME) as LATEST_APPLICATION_STATUS,
    ROUND(AVG(ltv.LTV_PCT), 2) as AVG_LTV_PCT,
    SUM(CASE WHEN aff.AFFORDABILITY_RESULT = 'PASS' THEN 1 ELSE 0 END) as AFFORDABILITY_PASS_COUNT,
    SUM(CASE WHEN aff.AFFORDABILITY_RESULT = 'FAIL' THEN 1 ELSE 0 END) as AFFORDABILITY_FAIL_COUNT,
    CURRENT_TIMESTAMP() as CALCULATION_TIMESTAMP
FROM {{ db }}.{{ loa_agg }}.LOAA_AGG_TB_APPLICATIONS a
LEFT JOIN ltv_calc ltv ON a.APPLICATION_ID = ltv.APPLICATION_ID
LEFT JOIN {{ db }}.{{ loa_agg }}.LOAA_AGG_TB_AFFORDABILITY_ASSESSMENTS aff ON a.APPLICATION_ID = aff.APPLICATION_ID
WHERE a.CUSTOMER_ID IS NOT NULL
GROUP BY a.CUSTOMER_ID;

DEFINE VIEW {{ db }}.{{ rep_agg }}.LOAR_AGG_VW_PORTFOLIO_CURRENT
COMMENT = 'Current portfolio snapshot - single row with all key metrics for executive dashboard. Returns latest portfolio statistics including total loans, average LTV, approval rates, and country breakdown.'
AS
SELECT
    (SELECT SUM(LOAN_COUNT) FROM {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_PORTFOLIO_SUMMARY WHERE AS_OF_DATE = CURRENT_DATE()) as TOTAL_LOANS,
    (SELECT SUM(TOTAL_REQUESTED_AMOUNT) FROM {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_PORTFOLIO_SUMMARY WHERE AS_OF_DATE = CURRENT_DATE()) as TOTAL_EXPOSURE,
    (SELECT ROUND(AVG(AVG_REQUESTED_AMOUNT), 0) FROM {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_PORTFOLIO_SUMMARY WHERE AS_OF_DATE = CURRENT_DATE()) as AVG_LOAN_AMOUNT,

    (SELECT ROUND(AVG(AVG_LTV_PCT), 2) FROM {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_LTV_DISTRIBUTION WHERE AS_OF_DATE = CURRENT_DATE()) as AVG_LTV_PCT,
    (SELECT SUM(LOAN_COUNT) FROM {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_LTV_DISTRIBUTION WHERE AS_OF_DATE = CURRENT_DATE() AND LTV_BUCKET IN ('80-90%', '>90%')) as HIGH_LTV_COUNT,

    (SELECT SUM(TOTAL_APPLICATIONS) FROM {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_APPLICATION_FUNNEL WHERE AS_OF_DATE = CURRENT_DATE()) as TOTAL_APPLICATIONS,
    (SELECT ROUND(AVG(APPROVAL_RATE_PCT), 2) FROM {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_APPLICATION_FUNNEL WHERE AS_OF_DATE = CURRENT_DATE()) as AVG_APPROVAL_RATE_PCT,

    (SELECT SUM(ASSESSMENT_COUNT) FROM {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_AFFORDABILITY_SUMMARY WHERE AS_OF_DATE = CURRENT_DATE()) as TOTAL_ASSESSMENTS,
    (SELECT ROUND(AVG(PASS_RATE_PCT), 2) FROM {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_AFFORDABILITY_SUMMARY WHERE AS_OF_DATE = CURRENT_DATE()) as AVG_AFFORDABILITY_PASS_RATE_PCT,

    (SELECT SUM(LOAN_COUNT) FROM {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_PORTFOLIO_SUMMARY WHERE AS_OF_DATE = CURRENT_DATE() AND COUNTRY = 'CHE') as SWITZERLAND_LOANS,
    (SELECT SUM(LOAN_COUNT) FROM {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_PORTFOLIO_SUMMARY WHERE AS_OF_DATE = CURRENT_DATE() AND COUNTRY = 'GBR') as UK_LOANS,
    (SELECT SUM(LOAN_COUNT) FROM {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_PORTFOLIO_SUMMARY WHERE AS_OF_DATE = CURRENT_DATE() AND COUNTRY = 'DEU') as GERMANY_LOANS,

    CURRENT_DATE() as AS_OF_DATE,
    CURRENT_TIMESTAMP() as REPORT_TIMESTAMP;

DEFINE VIEW {{ db }}.{{ rep_agg }}.LOAR_AGG_VW_LTV_DISTRIBUTION
COMMENT = 'LTV distribution by buckets for risk analysis charts. Shows loan counts and values across LTV ranges for regulatory reporting and risk concentration monitoring.'
AS
SELECT
    AS_OF_DATE,
    LTV_BUCKET,
    LTV_BUCKET_SORT_ORDER,
    LOAN_COUNT,
    TOTAL_LOAN_AMOUNT,
    AVG_LTV_PCT,
    TOTAL_COLLATERAL_VALUE,
    PCT_OF_TOTAL_LOANS,
    CALCULATION_TIMESTAMP
FROM {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_LTV_DISTRIBUTION
WHERE AS_OF_DATE = CURRENT_DATE()
ORDER BY LTV_BUCKET_SORT_ORDER;

DEFINE VIEW {{ db }}.{{ rep_agg }}.LOAR_AGG_VW_APPLICATION_FUNNEL
COMMENT = 'Application funnel metrics by product, country, and channel. Shows volumes, approval rates, and conversion metrics for origination performance monitoring.'
AS
SELECT
    AS_OF_DATE,
    PRODUCT_TYPE,
    COUNTRY,
    CHANNEL,
    TOTAL_APPLICATIONS,
    APPROVED_COUNT,
    DECLINED_COUNT,
    UNDER_REVIEW_COUNT,
    APPROVAL_RATE_PCT,
    DECLINE_RATE_PCT,
    AVG_REQUESTED_AMOUNT,
    CALCULATION_TIMESTAMP
FROM {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_APPLICATION_FUNNEL
WHERE AS_OF_DATE = CURRENT_DATE()
ORDER BY TOTAL_APPLICATIONS DESC;

DEFINE VIEW {{ db }}.{{ rep_agg }}.LOAR_AGG_VW_AFFORDABILITY_ANALYSIS
COMMENT = 'Affordability assessment analysis by country and outcome. Shows DTI/DSTI metrics and pass rates for regulatory compliance and underwriting quality monitoring.'
AS
SELECT
    AS_OF_DATE,
    COUNTRY,
    AFFORDABILITY_RESULT,
    ASSESSMENT_COUNT,
    AVG_DTI_RATIO_PCT,
    AVG_DSTI_RATIO_PCT,
    AVG_GROSS_INCOME,
    AVG_DEBT_OBLIGATIONS,
    PASS_RATE_PCT,
    CALCULATION_TIMESTAMP
FROM {{ db }}.{{ rep_agg }}.LOAR_AGG_DT_AFFORDABILITY_SUMMARY
WHERE AS_OF_DATE = CURRENT_DATE()
ORDER BY COUNTRY, AFFORDABILITY_RESULT;

DEFINE VIEW {{ db }}.{{ rep_agg }}.LOAR_AGG_VW_COMPLIANCE_SCREENING
COMMENT = 'Loan applications linked to sanctions and PEP screening status. Shows applications requiring compliance review or blocked due to sanctions/PEP hits.'
AS
SELECT
    a.APPLICATION_ID,
    a.CUSTOMER_ID,
    c.FULL_NAME,
    a.COUNTRY,
    a.REQUESTED_AMOUNT,
    a.STATUS as APPLICATION_STATUS,
    c.REQUIRES_SANCTIONS_REVIEW,
    c.REQUIRES_EXPOSED_PERSON_REVIEW,
    c.OVERALL_RISK_RATING,
    c.VULNERABLE_CUSTOMER_FLAG,
    c.SANCTIONS_MATCH_NAME,
    c.SANCTIONS_AUTHORITY,
    c.SANCTIONS_RISK_SCORE,
    c.EXPOSED_PERSON_EXACT_MATCH_NAME,
    c.EXPOSED_PERSON_EXACT_CATEGORY,
    c.EXPOSED_PERSON_EXACT_RISK_LEVEL,
    c.EXPOSED_PERSON_MATCH_TYPE,
    a.APPLICATION_DATE_TIME,
    CASE 
        WHEN c.REQUIRES_SANCTIONS_REVIEW = TRUE OR c.REQUIRES_EXPOSED_PERSON_REVIEW = TRUE THEN TRUE
        ELSE FALSE
    END as COMPLIANCE_HOLD_FLAG,
    CASE
        WHEN c.REQUIRES_SANCTIONS_REVIEW = TRUE THEN 'SANCTIONS_REVIEW'
        WHEN c.REQUIRES_EXPOSED_PERSON_REVIEW = TRUE THEN 'PEP_REVIEW'
        WHEN c.OVERALL_RISK_RATING IN ('CRITICAL', 'HIGH') THEN 'HIGH_RISK_REVIEW'
        ELSE 'CLEAR'
    END as COMPLIANCE_STATUS
FROM {{ db }}.{{ loa_agg }}.LOAA_AGG_TB_APPLICATIONS a
LEFT JOIN {{ db }}.{{ crm_agg }}.CRMA_AGG_DT_CUSTOMER_360 c ON a.CUSTOMER_ID = c.CUSTOMER_ID
WHERE a.CUSTOMER_ID IS NOT NULL
ORDER BY a.APPLICATION_DATE_TIME DESC;
